# =============================================================================
# resolve-merge.ps1 — Apply standard merge conflict resolutions (Windows)
# GENERATED by Retort v3.1.0 — regenerated on every sync
# =============================================================================
# Usage: .github\scripts\resolve-merge.ps1 [-Target dev]
#
# Merges origin/<target-branch> into the current branch and auto-resolves
# generated/framework-managed files per the Retort merge resolution matrix.
# Remaining conflicts (engine source, spec files) are listed for manual review.
# =============================================================================
param(
    [string]$Target = "main"
)

$ErrorActionPreference = "Stop"

$RepoRoot = git rev-parse --show-toplevel
Push-Location $RepoRoot

function Write-Info  { param([string]$msg) Write-Host "[info]  $msg" -ForegroundColor Cyan }
function Write-Ok    { param([string]$msg) Write-Host "[ok]    $msg" -ForegroundColor Green }
function Write-Warn  { param([string]$msg) Write-Host "[warn]  $msg" -ForegroundColor Yellow }
function Write-Err   { param([string]$msg) Write-Host "[error] $msg" -ForegroundColor Red }

try {
    # -----------------------------------------------------------------------
    # 1. Fetch and attempt merge
    # -----------------------------------------------------------------------
    Write-Info "Fetching origin/${Target}..."
    git fetch origin $Target 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Err "Failed to fetch origin/${Target}. Check your remote."
        exit 1
    }

    $currentBranch = git branch --show-current
    Write-Info "Merging origin/${Target} into ${currentBranch}..."

    git merge "origin/${Target}" --no-edit 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Ok "Merge completed cleanly — no conflicts."
        exit 0
    }

    Write-Info "Merge conflicts detected. Applying resolution matrix..."

    # -----------------------------------------------------------------------
    # 2. Auto-resolve generated files (KEEP_THEIRS — accept upstream)
    # -----------------------------------------------------------------------
    $generatedPatterns = @(
        '\.agents/skills/.*/SKILL\.md'
        '\.github/agents/.*\.agent\.md'
        '\.github/chatmodes/.*\.chatmode\.md'
        '\.github/prompts/.*\.prompt\.md'
        'docs/.*/README\.md'
        '\.github/copilot-instructions\.md'
        '\.github/PULL_REQUEST_TEMPLATE\.md'
    )

    $autoResolved = 0
    $conflicted = git diff --name-only --diff-filter=U 2>$null
    if (-not $conflicted) { $conflicted = @() }

    foreach ($file in $conflicted) {
        if (-not $file) { continue }
        $isGenerated = $false
        foreach ($pattern in $generatedPatterns) {
            if ($file -match "^$pattern$") {
                $isGenerated = $true
                break
            }
        }
        if ($isGenerated) {
            git checkout --theirs -- $file 2>$null
            git add $file 2>$null
            Write-Ok "Auto-resolved (accept upstream): $file"
            $autoResolved++
        }
    }

    # -----------------------------------------------------------------------
    # 3. Auto-resolve lockfiles (KEEP_THEIRS)
    # -----------------------------------------------------------------------
    $lockfiles = @(
        'pnpm-lock.yaml',
        '.agentkit/pnpm-lock.yaml',
        'package-lock.json',
        '.agentkit/package-lock.json'
    )

    $conflicted = git diff --name-only --diff-filter=U 2>$null
    if (-not $conflicted) { $conflicted = @() }

    foreach ($lockfile in $lockfiles) {
        if ($conflicted -contains $lockfile) {
            git checkout --theirs -- $lockfile 2>$null
            git add $lockfile 2>$null
            Write-Ok "Auto-resolved (accept upstream): $lockfile"
            $autoResolved++
        }
    }

    # -----------------------------------------------------------------------
    # 4. Auto-resolve generated config (KEEP_THEIRS)
    # -----------------------------------------------------------------------
    $generatedConfigs = @('.gemini/config.yaml')

    $conflicted = git diff --name-only --diff-filter=U 2>$null
    if (-not $conflicted) { $conflicted = @() }

    foreach ($config in $generatedConfigs) {
        if ($conflicted -contains $config) {
            git checkout --theirs -- $config 2>$null
            git add $config 2>$null
            Write-Ok "Auto-resolved (accept upstream): $config"
            $autoResolved++
        }
    }

    # -----------------------------------------------------------------------
    # 5. Report remaining conflicts
    # -----------------------------------------------------------------------
    $remaining = git diff --name-only --diff-filter=U 2>$null
    if (-not $remaining) { $remaining = @() }

    Write-Host ""
    Write-Info "Auto-resolved: ${autoResolved} file(s)"

    if ($remaining.Count -gt 0) {
        Write-Host ""
        Write-Warn "Manual merge required for the following file(s):"
        Write-Host ""
        foreach ($file in $remaining) {
            if (-not $file) { continue }
            switch -Wildcard ($file) {
                ".agentkit/engines/*" {
                    Write-Host "  [engine]  $file — semantic merge required (runtime logic)" -ForegroundColor Red
                }
                ".agentkit/spec/*" {
                    Write-Host "  [spec]    $file — preserve both intents" -ForegroundColor Yellow
                }
                default {
                    Write-Host "  [source]  $file" -ForegroundColor Cyan
                }
            }
        }
        Write-Host ""
        Write-Info "Resolve the files above, then run: git add -A; git commit"
        exit 1
    }
    else {
        Write-Ok "All conflicts resolved automatically."
        Write-Info "Committing merge..."
        git commit --no-edit
        Write-Ok "Merge committed successfully."

        $changedFiles = git diff --name-only "HEAD~1..HEAD" 2>$null
        if ($changedFiles -match "lock\.(yaml|json)$") {
            Write-Host ""
            Write-Warn "Lockfiles were updated. Consider running: pnpm install"
        }
    }
}
finally {
    Pop-Location
}
