#!/usr/bin/env bash
# GENERATED by Retort v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm --dir .agentkit retort:sync
# ---------------------------------------------------------------------------
# Hook: PreToolUse (matcher: Bash)
# Purpose: Before a git push, validate:
#   1. No generated-file drift (agentkit sync has been run)
#   2. All commit messages follow Conventional Commits
#   3. Branch name follows type/description pattern
# Stdin:   JSON with tool_input containing the command
# Stdout:  JSON with decision "block" + reason on failure
# ---------------------------------------------------------------------------
set -euo pipefail

# -- Read JSON payload from stdin ------------------------------------------
INPUT=$(cat)

# Only intercept git push commands
if ! command -v jq &>/dev/null; then
    exit 0
fi

COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')
CWD="${CWD:-$PWD}"

# Only trigger on git push
if [[ ! "$COMMAND" =~ ^git\ push ]]; then
    exit 0
fi

ERRORS=""

# -- Check 1: Generated file drift (skipped) ------------------------------
# autoSyncOnPush is disabled — skipping sync validation.
# Run 'pnpm -C .agentkit retort:sync' manually before pushing if you've edited spec files.

# -- Check 2: Conventional Commits on unpushed commits --------------------
# Get commits that would be pushed
BRANCH=$(git -C "$CWD" branch --show-current 2>/dev/null || echo "")
DEFAULT_BRANCH=$(git -C "$CWD" symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
if [[ -n "$BRANCH" ]]; then
    UPSTREAM=$(git -C "$CWD" rev-parse --abbrev-ref "@{upstream}" 2>/dev/null || echo "")
    if [[ -n "$UPSTREAM" ]]; then
        RANGE="${UPSTREAM}..HEAD"
    else
        # No upstream yet — check last 20 commits against default branch
        if git -C "$CWD" rev-parse "origin/${DEFAULT_BRANCH}" &>/dev/null; then
            RANGE="origin/${DEFAULT_BRANCH}..HEAD"
        else
            RANGE="HEAD~20..HEAD"
        fi
    fi

    CC_PATTERN='^(feat|fix|docs|style|refactor|test|chore|ci|perf|build|revert)(\(.+\))?!?:.+'
    BAD_COMMITS=""
    while IFS= read -r line; do
        HASH=$(echo "$line" | cut -d' ' -f1)
        MSG=$(echo "$line" | cut -d' ' -f2-)
        if [[ ! "$MSG" =~ $CC_PATTERN ]]; then
            BAD_COMMITS="${BAD_COMMITS}  ${HASH} ${MSG}\n"
        fi
    done < <(git -C "$CWD" log --oneline "$RANGE" 2>/dev/null || true)

    if [[ -n "$BAD_COMMITS" ]]; then
        ERRORS="${ERRORS}CONVENTIONAL COMMITS VIOLATION — The following commits do not follow the format 'type(scope): description':\n${BAD_COMMITS}Types: feat, fix, docs, style, refactor, test, chore, ci, perf, build, revert\n\n"
    fi
fi

# -- Check 3: Branch name follows type/description pattern -----------------
# Skip check for default branch and claude/ prefixed branches (agent sessions)
if [[ -n "$BRANCH" ]]; then
    BRANCH_PATTERN='^(feat|fix|docs|style|refactor|test|chore|ci|perf|build|revert|release|hotfix|claude)/[a-z0-9][a-z0-9._-]+$'
    if [[ "$BRANCH" != "$DEFAULT_BRANCH" ]] && [[ "$BRANCH" != "develop" ]] && [[ ! "$BRANCH" =~ ^release/ ]] && [[ ! "$BRANCH" =~ $BRANCH_PATTERN ]]; then
        ERRORS="${ERRORS}BRANCH NAMING VIOLATION — Branch '${BRANCH}' does not follow the pattern type/short-description.\nExpected: feat/*, fix/*, docs/*, chore/*, ci/*, refactor/*, test/*, etc.\nExample: feat/add-user-auth, fix/token-refresh\n\n"
    fi
fi

# -- Emit block decision if errors found ----------------------------------
if [[ -n "$ERRORS" ]]; then
    # Pass reason via stdin to avoid E2BIG on Windows Git Bash (issue #453)
    printf '%b' "$ERRORS" | jq -Rs '{"decision": "block", "reason": .}'
    exit 0
fi

exit 0
