#!/usr/bin/env bash
# GENERATED by Retort v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm -C .agentkit agentkit:sync
# ---------------------------------------------------------------------------
# Hook: PreToolUse (matcher: Write|Edit)
# Purpose: Block AI writes to AgentKit Forge source files (templates, spec,
#          engines, overlays) in DOWNSTREAM repos. In the agentkit-forge source
#          repo itself, agents ARE the maintainers and need full access.
# Stdin:   JSON with session_id, cwd, hook_event_name, tool_name, tool_input
# Stdout:  JSON deny response on match, empty otherwise
# ---------------------------------------------------------------------------
set -euo pipefail

INPUT=$(cat)

FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [[ -z "$FILE_PATH" ]]; then
    exit 0
fi

# -- Source repo detection -----------------------------------------------------
# If we are in the agentkit-forge source repo, agents are maintaining the
# templates and engine — protection is not needed. Detection: check if
# .agentkit/package.json name is "agentkit-forge" (the upstream source repo).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTKIT_PKG="${SCRIPT_DIR}/../../.agentkit/package.json"

if [[ -f "$AGENTKIT_PKG" ]]; then
    PKG_NAME=$(jq -r '.name // empty' "$AGENTKIT_PKG" 2>/dev/null || true)
    if [[ "$PKG_NAME" == "agentkit-forge-runtime" ]]; then
        # This IS the agentkit-forge source repo — agents maintain these files.
        exit 0
    fi
fi

# -- Protected directory patterns ---------------------------------------------
# In downstream repos, these are the upstream source-of-truth paths. AI agents
# must not modify them directly. Instead, propose changes via a PR to the forge
# repo, or modify .agentkit/spec/ and run sync to regenerate.
PROTECTED_PATTERNS=(
    '\.agentkit/templates/'
    '\.agentkit/spec/'
    '\.agentkit/engines/'
    '\.agentkit/overlays/'
    '\.agentkit/bin/'
)

for pattern in "${PROTECTED_PATTERNS[@]}"; do
    if echo "$FILE_PATH" | grep -qE "$pattern"; then
        jq -n \
            --arg reason "Blocked: '${FILE_PATH}' is an AgentKit Forge source file. These files are the upstream source-of-truth and must not be modified directly by AI agents. To propose changes, create a PR to the agentkit-forge repository targeting the relevant spec or template. If you need to change project configuration, edit the YAML specs in .agentkit/spec/ and run 'pnpm -C .agentkit agentkit:sync'." \
            '{
                hookSpecificOutput: {
                    hookEventName: "PreToolUse",
                    permissionDecision: "deny",
                    permissionDecisionReason: $reason
                }
            }'
        exit 0
    fi
done

exit 0
