#!/usr/bin/env pwsh
# GENERATED by Retort — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm --dir .agentkit retort:sync
# ---------------------------------------------------------------------------
# Hook: SessionStart
# Purpose: Detect installed tooling, show git status, and return environment
#          context so Claude has an accurate picture of the workspace.
# Stdin:   JSON with session_id, cwd, hook_event_name, etc.
# Stdout:  JSON with hookSpecificOutput.additionalContext
# ---------------------------------------------------------------------------
$ErrorActionPreference = "Stop"

# -- Read JSON payload from stdin ------------------------------------------
try {
    $rawInput = @($input) -join ""
    $data = $rawInput | ConvertFrom-Json
} catch {
    $data = $null
}

$sessionId  = if ($data -and $data.PSObject.Properties['session_id'])  { $data.session_id }  else { "" }
$cwd        = if ($data -and $data.PSObject.Properties['cwd'])         { $data.cwd }         else { $PWD.Path }

if ([string]::IsNullOrWhiteSpace($cwd)) { $cwd = $PWD.Path }

# -- Detect installed tooling ----------------------------------------------
$toolsFound = [System.Collections.Generic.List[string]]::new()

function Test-Tool {
    param([string]$Name, [string]$Command)
    try {
        $cmd = Get-Command $Command -ErrorAction SilentlyContinue
        if ($cmd) {
            $lines = @(& $Command --version 2>&1 | ForEach-Object { ([string]$_) -replace "`0", "" })
            $ver = $lines | Where-Object { $_ -and $_.Trim() -ne '' -and $_ -notmatch '^(?i)warning:' } | Select-Object -First 1
            if (-not $ver) {
                $ver = $lines | Where-Object { $_ -and $_.Trim() -ne '' } | Select-Object -First 1
            }
            if ($ver) {
                $text = [string]$ver
                if ($text -notmatch '(?i)class not registered|not recognized|not found|no such file|cannot find') {
                    $toolsFound.Add("${Name}: ${text}")
                }
            }
        }
    } catch {
        # Tool not available -- skip.
    }
}

Test-Tool -Name "Git"      -Command "git"
Test-Tool -Name "GitHub CLI" -Command "gh"
Test-Tool -Name "jq"       -Command "jq"
Test-Tool -Name "Bash"     -Command "bash"
Test-Tool -Name "PowerShell" -Command "pwsh"

Test-Tool -Name "Node.js"  -Command "node"
Test-Tool -Name "pnpm"     -Command "pnpm"
Test-Tool -Name "npm"      -Command "npm"

Test-Tool -Name "Docker"   -Command "docker"
Test-Tool -Name "Azure CLI" -Command "az"
Test-Tool -Name "Terraform" -Command "terraform"

if ($toolsFound.Count -gt 0) {
    $toolsSummary = $toolsFound -join "`n"
} else {
    $toolsSummary = "No recognised toolchains detected."
}

# -- Git information -------------------------------------------------------
$gitSummary = ""
try {
    $isGit = & git -C $cwd rev-parse --is-inside-work-tree 2>$null
    if ($isGit -eq "true") {
        $gitBranch = & git -C $cwd branch --show-current 2>$null
        if ([string]::IsNullOrWhiteSpace($gitBranch)) { $gitBranch = "detached" }
        $gitStatus = & git -C $cwd status --short 2>$null
        $dirtyCount = 0
        if ($gitStatus) {
            $dirtyCount = @($gitStatus).Count
        }
        $gitSummary = "Branch: $gitBranch | Uncommitted files: $dirtyCount"
    } else {
        $gitSummary = "Not a git repository (or git is not installed)."
    }
} catch {
    $gitSummary = "Not a git repository (or git is not installed)."
}

# -- Compose environment summary -------------------------------------------
$envSummary = @"
Session: $sessionId
Working directory: $cwd

Language profile source: configured (confidence: high)

Toolchains:
$toolsSummary

Git:
$gitSummary
"@

# -- Return structured output ----------------------------------------------
$output = @{
    hookSpecificOutput = @{
        additionalContext = $envSummary
    }
} | ConvertTo-Json -Depth 5

Write-Output $output
exit 0
