#!/usr/bin/env bash
# GENERATED by Retort v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm -C .agentkit retort:sync
# ---------------------------------------------------------------------------
# Hook: SessionStart
# Purpose: Detect installed tooling, show git status, and return environment
#          context so Claude has an accurate picture of the workspace.
# Stdin:   JSON with session_id, cwd, hook_event_name, etc.
# Stdout:  JSON with hookSpecificOutput.additionalContext
# ---------------------------------------------------------------------------
set -euo pipefail

# ── Read JSON payload from stdin ──────────────────────────────────────────
INPUT=$(cat)

# Parse JSON — prefer jq if available, fall back to basic grep/sed extraction
if command -v jq &>/dev/null; then
  SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
  CWD=$(echo "$INPUT" | jq -r '.cwd // empty')
else
  # Fallback: extract values with grep/sed (handles simple flat JSON)
  # Use POSIX character classes for portability (BSD/macOS grep lacks \s)
  SESSION_ID=$(echo "$INPUT" | grep -o '"session_id"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*: *"//;s/"$//' || true)
  CWD=$(echo "$INPUT" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*: *"//;s/"$//' || true)
fi

# Fall back to $PWD when cwd is not supplied.
CWD="${CWD:-$PWD}"

# ── Detect installed tooling ─────────────────────────────────────────────
declare -a tools_found=()

detect_tool() {
    local name="$1"
    local cmd="$2"
    if command -v "$cmd" &>/dev/null; then
        local ver
        if ver=$("$cmd" --version 2>/dev/null | head -n1); then
            if [[ -n "$ver" ]]; then
                tools_found+=("${name}: ${ver}")
            else
                tools_found+=("${name}: installed")
            fi
        fi
    fi
}

detect_tool "Git"      "git"
detect_tool "GitHub CLI" "gh"
detect_tool "jq"       "jq"
detect_tool "Bash"     "bash"
detect_tool "PowerShell" "pwsh"

detect_tool "Node.js"  "node"
detect_tool "pnpm"     "pnpm"
detect_tool "npm"      "npm"

detect_tool "Docker"   "docker"
detect_tool "Azure CLI" "az"
detect_tool "Terraform" "terraform"

tools_summary=""
if [[ ${#tools_found[@]} -gt 0 ]]; then
    tools_summary=$(printf '%s\n' "${tools_found[@]}")
else
    tools_summary="No recognised toolchains detected."
fi

# ── Git information ──────────────────────────────────────────────────────
git_summary=""
if command -v git &>/dev/null && git -C "$CWD" rev-parse --is-inside-work-tree &>/dev/null; then
    git_branch=$(git -C "$CWD" branch --show-current 2>/dev/null || echo "detached")
    git_status=$(git -C "$CWD" status --short 2>/dev/null || true)
    dirty_count=0
    if [[ -n "$git_status" ]]; then
        dirty_count=$(echo "$git_status" | wc -l | tr -d ' ')
    fi
    git_summary="Branch: ${git_branch} | Uncommitted files: ${dirty_count}"
else
    git_summary="Not a git repository (or git is not installed)."
fi

# ── Session cost tracking ───────────────────────────────────────────────
# Write a session-start event to the JSONL usage log for cost tracking.
AGENTKIT_ROOT=""
if [[ -d "${CWD}/.agentkit" ]]; then
    AGENTKIT_ROOT="${CWD}/.agentkit"
elif [[ -d "${CWD}/../.agentkit" ]]; then
    AGENTKIT_ROOT="${CWD}/../.agentkit"
fi

if [[ -n "$AGENTKIT_ROOT" ]] && command -v node &>/dev/null; then
    LOG_DIR="${AGENTKIT_ROOT}/logs"
    mkdir -p "$LOG_DIR"
    DATE_STR=$(date -u +"%Y-%m-%d")
    LOG_FILE="${LOG_DIR}/usage-${DATE_STR}.jsonl"
    TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")

    git_user=""
    if command -v git &>/dev/null; then
        _raw_email=$(git -C "$CWD" config user.email 2>/dev/null || echo "")
        if [[ -n "$_raw_email" ]]; then
            # Hash the email for privacy — avoids logging PII in shared repos/CI
            git_user=$(echo -n "$_raw_email" | sha256sum 2>/dev/null | cut -c1-12 || echo "unknown")
        else
            git_user="unknown"
        fi
    fi

    if command -v jq &>/dev/null; then
        jq -n --arg ts "$TIMESTAMP" --arg sid "$SESSION_ID" --arg user "$git_user" \
            --arg branch "${git_branch:-unknown}" --arg cwd "$CWD" \
            '{timestamp: $ts, event: "session_start", sessionId: $sid, user: $user, branch: $branch, cwd: $cwd}' \
            >> "$LOG_FILE" 2>/dev/null || true
    fi
fi

# ── Convention reminders ────────────────────────────────────────────────
conventions_reminder="REMINDERS:
- Commits & PR titles MUST use Conventional Commits: type(scope): description
  Types: feat|fix|docs|style|refactor|test|chore|ci|perf|build|revert
- After editing .agentkit/spec/, run: pnpm -C .agentkit agentkit:sync
- Run /check before creating a PR"

# ── Compose the environment summary ─────────────────────────────────────
env_summary=$(printf 'Session: %s\nWorking directory: %s\nLanguage profile source: configured (confidence: high)\n\nToolchains:\n%s\n\nGit:\n%s\n\n%s' \
    "$SESSION_ID" "$CWD" "$tools_summary" "$git_summary" "$conventions_reminder")

# ── Return structured output ────────────────────────────────────────────
if command -v jq &>/dev/null; then
  jq -n --arg ctx "$env_summary" '{
      hookSpecificOutput: {
          additionalContext: $ctx
      }
  }'
else
  # Fallback: manually construct JSON (escape backslashes, quotes, and newlines)
  escaped_summary=$(printf '%s' "$env_summary" | awk '{gsub(/\\/, "\\\\"); gsub(/"/, "\\\""); printf "%s\\n", $0}' | sed '$ s/\\n$//')
  printf '{"hookSpecificOutput":{"additionalContext":"%s"}}\n' "$escaped_summary"
fi

exit 0
