# GENERATED by AgentKit Forge v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/agentkit-forge
# Regenerate: pnpm -C .agentkit agentkit:sync
# ---------------------------------------------------------------------------
# setup-branch-protection.ps1
# Configures GitHub branch protection rules for the default branch.
# Generated by AgentKit Forge — run once after initial setup.
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth status)
#   - Admin access to the repository
#
# Usage:
#   .github/scripts/setup-branch-protection.ps1 [-Branch main] [-DryRun]
# ---------------------------------------------------------------------------

param(
    [string]$Branch = "main",
    [switch]$DryRun,
    [switch]$Help
)

$ErrorActionPreference = 'Stop'

if ($Help) {
    Write-Host "Usage: setup-branch-protection.ps1 [-Branch main] [-DryRun]"
    Write-Host ""
    Write-Host "Configures GitHub branch protection for the specified branch."
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -Branch NAME   Branch to protect (default: main)"
    Write-Host "  -DryRun        Print the API payload without applying"
    Write-Host "  -Help          Show this help"
    exit 0
}

# -- Verify prerequisites ---------------------------------------------------
if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Error "gh CLI is not installed. Install from https://cli.github.com/"
    exit 1
}

$authCheck = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "gh CLI is not authenticated. Run 'gh auth login' first."
    exit 1
}

# -- Detect repository -------------------------------------------------------
$Repo = gh repo view --json nameWithOwner -q '.nameWithOwner' 2>$null
if (-not $Repo) {
    Write-Error "Could not detect repository. Run this from within a git repo."
    exit 1
}

Write-Host "=== AgentKit Forge - Branch Protection Setup ==="
Write-Host ""
Write-Host "Repository: $Repo"
Write-Host "Branch:     $Branch"
Write-Host ""

# -- Build the branch protection payload ------------------------------------
$Payload = @{
    required_status_checks = @{
        strict   = $true
        contexts = @(
            "AgentKit Forge CI / Test (ubuntu-latest)",
            "AgentKit Forge CI / Test (windows-latest)",
            "AgentKit Forge CI / Test (macos-latest)",
            "AgentKit Forge CI / Validate",
            "Branch Protection / branch-rules"
        )
    }
    enforce_admins = $false
    required_pull_request_reviews = @{
        required_approving_review_count = 1
        dismiss_stale_reviews           = $true
        require_code_owner_reviews      = $true
        require_last_push_approval      = $false
    }
    restrictions                    = $null
    required_linear_history         = $true
    allow_force_pushes              = $false
    allow_deletions                 = $false
    block_creations                 = $false
    required_conversation_resolution = $true
} | ConvertTo-Json -Depth 4

# -- Apply or preview -------------------------------------------------------
if ($DryRun) {
    Write-Host "[dry-run] Would apply the following branch protection to $Repo/$Branch:"
    Write-Host ""
    Write-Host $Payload
    Write-Host ""
    Write-Host "[dry-run] Run without -DryRun to apply."
    exit 0
}

Write-Host "Applying branch protection rules..."
Write-Host ""

$Payload | gh api --method PUT "/repos/$Repo/branches/$Branch/protection" --input -

Write-Host ""
Write-Host "Branch protection applied successfully."
Write-Host ""
Write-Host "Configured:"
Write-Host "  - Required status checks: CI / test, CI / validate, Branch Protection / branch-rules (strict: up-to-date)"
Write-Host "  - Required PR reviews: 1 approval, dismiss stale, require CODEOWNERS"
Write-Host "  - Required conversation resolution: enabled"
Write-Host "  - Required linear history: enabled (squash-merge)"
Write-Host "  - Force pushes: blocked"
Write-Host "  - Branch deletion: blocked"
Write-Host ""

# -- Create labels -----------------------------------------------------------
Write-Host "Ensuring labels exist..."

function New-LabelIfMissing {
    param([string]$Name, [string]$Color, [string]$Description)

    $existing = gh label view $Name --repo $Repo 2>$null
    if ($LASTEXITCODE -ne 0) {
        gh label create $Name --color $Color --description $Description --repo $Repo
        Write-Host "  Created label: $Name"
    } else {
        Write-Host "  Label exists: $Name"
    }
}

New-LabelIfMissing "forge-source-change"    "d93f0b" "PR modifies AgentKit Forge source files"
New-LabelIfMissing "needs-maintainer-review" "e4e669" "Requires maintainer review before merge"
New-LabelIfMissing "dependencies"           "0075ca" "Dependency updates"
New-LabelIfMissing "breaking-change"        "b60205" "Contains breaking changes"
New-LabelIfMissing "security"               "d93f0b" "Security-related changes"

Write-Host ""
Write-Host "Done. Run 'gh api /repos/$Repo/branches/$Branch/protection' to verify."
