# GENERATED by AgentKit Forge v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/agentkit-forge
# Regenerate: pnpm -C .agentkit agentkit:sync
# ---------------------------------------------------------------------------
# setup-branch-protection.ps1
# Configures GitHub branch protection rules, repository settings, code
# scanning rulesets, and Copilot review for the default branch.
# Generated by AgentKit Forge — run once after initial setup.
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth status)
#   - Admin access to the repository
#   - GitHub Advanced Security enabled (for code scanning rulesets)
#
# Usage:
#   .github/scripts/setup-branch-protection.ps1 [-Branch main] [-DryRun]
# ---------------------------------------------------------------------------

param(
    [string]$Branch = "main",
    [switch]$DryRun,
    [switch]$Help
)

$ErrorActionPreference = 'Stop'

if ($Help) {
    Write-Host "Usage: setup-branch-protection.ps1 [-Branch main] [-DryRun]"
    Write-Host ""
    Write-Host "Configures GitHub branch protection for the specified branch."
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -Branch NAME   Branch to protect (default: main)"
    Write-Host "  -DryRun        Print the API payloads without applying"
    Write-Host "  -Help          Show this help"
    exit 0
}

# -- Validate branch name (prevent injection) ------------------------------
if ($Branch -notmatch '^[a-zA-Z0-9._/\-]+$') {
    Write-Error "Invalid branch name '$Branch'. Only alphanumeric, '.', '_', '/', and '-' are allowed."
    exit 1
}

# -- Verify prerequisites ---------------------------------------------------
if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Error "gh CLI is not installed. Install from https://cli.github.com/"
    exit 1
}

$authCheck = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "gh CLI is not authenticated. Run 'gh auth login' first."
    exit 1
}

# -- Detect repository -------------------------------------------------------
$Repo = gh repo view --json nameWithOwner -q '.nameWithOwner' 2>$null
if (-not $Repo) {
    Write-Error "Could not detect repository. Run this from within a git repo."
    exit 1
}

Write-Host "=== AgentKit Forge - Branch Protection Setup ==="
Write-Host ""
Write-Host "Repository: $Repo"
Write-Host "Branch:     $Branch"
Write-Host ""

# =============================================================================
# 1. Branch protection rules (legacy API)
# =============================================================================

$Payload = @"
{
  "required_status_checks": {
    "strict": true,
    "contexts": ["CI / test (ubuntu-latest, 24)","CI / validate","Branch Protection / branch-rules"]
  },
  "enforce_admins": false,
  "required_pull_request_reviews": {
    "required_approving_review_count": 1,
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": true,
    "require_last_push_approval": false
  },
  "restrictions": null,
  "required_linear_history": true,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "block_creations": false,
  "required_conversation_resolution": true
}
"@

if ($DryRun) {
    Write-Host "[dry-run] Would apply the following branch protection to $Repo/${Branch}:"
    Write-Host ""
    Write-Host $Payload
    Write-Host ""
} else {
    Write-Host "Applying branch protection rules..."
    $Payload | gh api --method PUT "/repos/$Repo/branches/$Branch/protection" --input -
    if ($LASTEXITCODE -ne 0) { throw "Failed to apply branch protection rules." }
    Write-Host "Branch protection applied."
}
Write-Host ""

# =============================================================================
# 2. Signed commits
# =============================================================================

# =============================================================================
# 3. Repository settings (merge strategies, auto-delete, auto-merge)
# =============================================================================

$RepoSettings = @"
{
  "allow_merge_commit": false,
  "allow_squash_merge": true,
  "allow_rebase_merge": false,
  "delete_branch_on_merge": true,
  "allow_auto_merge": false
}
"@

if ($DryRun) {
    Write-Host "[dry-run] Would apply the following repository settings to ${Repo}:"
    Write-Host ""
    Write-Host $RepoSettings
    Write-Host ""
} else {
    Write-Host "Applying repository merge settings..."
    $RepoSettings | gh api --method PATCH "/repos/$Repo" --input -
    if ($LASTEXITCODE -ne 0) { throw "Failed to apply repository settings." }
    Write-Host "Repository settings applied."
}
Write-Host ""

# =============================================================================
# 4. Code scanning ruleset (GitHub Rulesets API)
# =============================================================================

$CodeScanningRuleset = @"
{
  "name": "code-scanning",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/$Branch"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "code_scanning",
      "parameters": {
        "code_scanning_tools": [{"tool":"CodeQL","security_alerts_threshold":"high_or_higher","alerts_threshold":"errors"}]
      }
    }
  ]
}
"@

if ($DryRun) {
    Write-Host "[dry-run] Would create/update code scanning ruleset on ${Repo}:"
    Write-Host ""
    Write-Host $CodeScanningRuleset
    Write-Host ""
} else {
    Write-Host "Configuring code scanning ruleset..."
    $existingId = (gh api "/repos/$Repo/rulesets" --jq '[ .[] | select(.name == "code-scanning") | .id ] | first' 2>$null)
    if ($LASTEXITCODE -ne 0) { $existingId = $null }
    if ($existingId) {
        Write-Host "  Updating existing ruleset (ID: $existingId)..."
        $CodeScanningRuleset | gh api --method PUT "/repos/$Repo/rulesets/$existingId" --input -
    } else {
        Write-Host "  Creating new code scanning ruleset..."
        $CodeScanningRuleset | gh api --method POST "/repos/$Repo/rulesets" --input -
    }
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  Warning: Failed to configure code scanning ruleset. GitHub Advanced Security may not be enabled."
    } else {
        Write-Host "Code scanning ruleset applied."
    }
}
Write-Host ""

# =============================================================================
# 5. Copilot code review
# =============================================================================

$CopilotReview = @"
{
  "enabled": true,
  "review_new_pushes": true,
  "review_draft_pull_requests": true
}
"@

if ($DryRun) {
    Write-Host "[dry-run] Would enable Copilot code review on ${Repo}:"
    Write-Host ""
    Write-Host $CopilotReview
    Write-Host ""
} else {
    Write-Host "Enabling Copilot code review..."
    # Note: Requires GitHub Copilot subscription with code review enabled for the organization.
    # Endpoint may return 404 if Copilot code review is not available for this repo.
    $CopilotReview | gh api --method PUT "/repos/$Repo/copilot/code_review" --input - 2>$null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  Note: Copilot code review requires a Copilot-enabled organization."
    } else {
        Write-Host "Copilot code review configured."
    }
}
Write-Host ""

# =============================================================================
# 6. Merge queue
# =============================================================================

# =============================================================================
# 7. Labels
# =============================================================================

if ($DryRun) {
    Write-Host "[dry-run] Would ensure labels exist:"
    Write-Host "  - forge-source-change"
    Write-Host "  - needs-maintainer-review"
    Write-Host "  - dependencies"
    Write-Host "  - breaking-change"
    Write-Host "  - security"
} else {
    Write-Host "Ensuring labels exist..."

    function New-LabelIfMissing {
        param([string]$Name, [string]$Color, [string]$Description)

        $existing = gh label view $Name --repo $Repo 2>$null
        if ($LASTEXITCODE -ne 0) {
            gh label create $Name --color $Color --description $Description --repo $Repo
            Write-Host "  Created label: $Name"
        } else {
            Write-Host "  Label exists: $Name"
        }
    }

    New-LabelIfMissing "forge-source-change"    "d93f0b" "PR modifies AgentKit Forge source files"
    New-LabelIfMissing "needs-maintainer-review" "e4e669" "Requires maintainer review before merge"
    New-LabelIfMissing "dependencies"           "0075ca" "Dependency updates"
    New-LabelIfMissing "breaking-change"        "b60205" "Contains breaking changes"
    New-LabelIfMissing "security"               "d93f0b" "Security-related changes"
}

Write-Host ""

# =============================================================================
# Summary
# =============================================================================

Write-Host "=== Setup Complete ==="
Write-Host ""
Write-Host "Configured:"
Write-Host "  Branch protection ($Branch):"
Write-Host "    - Required status checks (strict: true)"
Write-Host "    - Required PR reviews: 1 approval(s), dismiss stale: true, CODEOWNERS: true"
Write-Host "    - Last push approval: false"
Write-Host "    - Conversation resolution: true"
Write-Host "    - Linear history: true"
Write-Host "    - Enforce admins: false"
Write-Host "    - Force pushes: false | Deletions: false"

Write-Host "  Repository settings:"
Write-Host "    - Squash merge: true | Merge commits: false | Rebase: false"
Write-Host "    - Delete branch on merge: true"
Write-Host "    - Auto-merge: false"

Write-Host "  Code scanning:"

Write-Host "    - CodeQL: security=high_or_higher, alerts=errors"

Write-Host "  Copilot code review:"
Write-Host "    - Auto-request: enabled"
Write-Host "    - Review new pushes: true"
Write-Host "    - Review draft PRs: true"

Write-Host ""
Write-Host "Run 'gh api /repos/$Repo/branches/$Branch/protection' to verify."
