#!/usr/bin/env bash
# GENERATED by Retort — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm --dir .agentkit retort:sync
# ---------------------------------------------------------------------------
# setup-branch-protection.sh
# Configures GitHub branch protection rules, repository settings, code
# scanning rulesets, and Copilot review for the default branch.
# Generated by Retort — run once after initial setup.
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth status)
#   - Admin access to the repository
#   - GitHub Advanced Security enabled (for code scanning rulesets)
#
# Usage:
#   .github/scripts/setup-branch-protection.sh [--branch main] [--dry-run]
# ---------------------------------------------------------------------------
set -euo pipefail

# -- Defaults ---------------------------------------------------------------
BRANCH="main"
DRY_RUN=false

# -- Parse arguments --------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --branch)  BRANCH="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        --help|-h)
            echo "Usage: $(basename "$0") [--branch main] [--dry-run]"
            echo ""
            echo "Configures GitHub branch protection for the specified branch."
            echo ""
            echo "Options:"
            echo "  --branch NAME   Branch to protect (default: main)"
            echo "  --dry-run       Print the API payloads without applying"
            echo "  --help          Show this help"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# -- Validate branch name (prevent injection) ------------------------------
if [[ ! "$BRANCH" =~ ^[a-zA-Z0-9._/-]+$ ]]; then
    echo "Error: Invalid branch name '$BRANCH'. Only alphanumeric, '.', '_', '/', and '-' are allowed."
    exit 1
fi

# -- Verify prerequisites ---------------------------------------------------
if ! command -v gh &>/dev/null; then
    echo "Error: gh CLI is not installed. Install from https://cli.github.com/"
    exit 1
fi

if ! gh auth status &>/dev/null; then
    echo "Error: gh CLI is not authenticated. Run 'gh auth login' first."
    exit 1
fi

# -- Detect repository -------------------------------------------------------
REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null)
if [[ -z "$REPO" ]]; then
    echo "Error: Could not detect repository. Run this from within a git repo."
    exit 1
fi

echo "=== Retort — Branch Protection Setup ==="
echo ""
echo "Repository: $REPO"
echo "Branch:     $BRANCH"
echo ""

# =============================================================================
# 1. Branch protection rules (legacy API)
# =============================================================================

PAYLOAD=$(cat <<ENDJSON
{
  "required_status_checks": {
    "strict": true,
    "contexts": ["Test","Validate","Prettier","branch-rules"]
  },
  "enforce_admins": false,
  "required_pull_request_reviews": {
    "required_approving_review_count": 1,
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": true,
    "require_last_push_approval": false
  },
  "restrictions": null,
  "required_linear_history": true,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "block_creations": false,
  "required_conversation_resolution": true
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would apply the following branch protection to $REPO/$BRANCH:"
    echo ""
    echo "$PAYLOAD" | python3 -m json.tool 2>/dev/null || echo "$PAYLOAD"
    echo ""
else
    echo "Applying branch protection rules..."
    gh api \
        --method PUT \
        "/repos/$REPO/branches/$BRANCH/protection" \
        --input - <<< "$PAYLOAD"
    echo "Branch protection applied."
fi
echo ""

# =============================================================================
# 2. Signed commits
# =============================================================================

# =============================================================================
# 3. Repository settings (merge strategies, auto-delete, auto-merge)
# =============================================================================

REPO_SETTINGS=$(cat <<'ENDJSON'
{
  "allow_merge_commit": false,
  "allow_squash_merge": true,
  "allow_rebase_merge": false,
  "delete_branch_on_merge": true,
  "allow_auto_merge": false
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would apply the following repository settings to $REPO:"
    echo ""
    echo "$REPO_SETTINGS" | python3 -m json.tool 2>/dev/null || echo "$REPO_SETTINGS"
    echo ""
else
    echo "Applying repository merge settings..."
    gh api \
        --method PATCH \
        "/repos/$REPO" \
        --input - <<< "$REPO_SETTINGS"
    echo "Repository settings applied."
fi
echo ""

# =============================================================================
# 4. Code scanning ruleset (GitHub Rulesets API)
# =============================================================================

CODE_SCANNING_RULESET=$(cat <<ENDJSON
{
  "name": "code-scanning",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/$BRANCH"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "code_scanning",
      "parameters": {
        "code_scanning_tools": [{"tool":"CodeQL","security_alerts_threshold":"high_or_higher","alerts_threshold":"errors"}]
      }
    }
  ]
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would create/update code scanning ruleset on $REPO:"
    echo ""
    echo "$CODE_SCANNING_RULESET" | python3 -m json.tool 2>/dev/null || echo "$CODE_SCANNING_RULESET"
    echo ""
else
    echo "Configuring code scanning ruleset..."
    # Check if a code-scanning ruleset already exists
    EXISTING_RULESET_ID=$(gh api "/repos/$REPO/rulesets" --jq '[ .[] | select(.name == "code-scanning") | .id ] | first' 2>/dev/null || true)
    if [[ -n "$EXISTING_RULESET_ID" ]]; then
        echo "  Updating existing ruleset (ID: $EXISTING_RULESET_ID)..."
        if ! gh api \
            --method PUT \
            "/repos/$REPO/rulesets/$EXISTING_RULESET_ID" \
            --input - <<< "$CODE_SCANNING_RULESET"; then
            echo "  Warning: Failed to update code scanning ruleset. GitHub Advanced Security may not be enabled."
        fi
    else
        echo "  Creating new code scanning ruleset..."
        if ! gh api \
            --method POST \
            "/repos/$REPO/rulesets" \
            --input - <<< "$CODE_SCANNING_RULESET"; then
            echo "  Warning: Failed to create code scanning ruleset. GitHub Advanced Security may not be enabled."
        fi
    fi
    echo "Code scanning ruleset applied."
fi
echo ""

# =============================================================================
# 5. Copilot code review
# =============================================================================

COPILOT_REVIEW=$(cat <<'ENDJSON'
{
  "enabled": true,
  "review_new_pushes": true,
  "review_draft_pull_requests": true
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would enable Copilot code review on $REPO:"
    echo ""
    echo "$COPILOT_REVIEW" | python3 -m json.tool 2>/dev/null || echo "$COPILOT_REVIEW"
    echo ""
else
    echo "Enabling Copilot code review..."
    # Note: Requires GitHub Copilot subscription with code review enabled for the organization.
    # Endpoint may return 404 if Copilot code review is not available for this repo.
    gh api \
        --method PUT \
        "/repos/$REPO/copilot/code_review" \
        --input - <<< "$COPILOT_REVIEW" \
        2>/dev/null || echo "  Note: Copilot code review requires a Copilot-enabled organization."
    echo "Copilot code review configured."
fi
echo ""

# =============================================================================
# 6. Merge queue
# =============================================================================

# =============================================================================
# 7. Labels
# =============================================================================

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would ensure labels exist:"
    echo "  - forge-source-change"
    echo "  - needs-maintainer-review"
    echo "  - dependencies"
    echo "  - breaking-change"
    echo "  - security"
else
    echo "Ensuring labels exist..."

    create_label_if_missing() {
        local name="$1" color="$2" description="$3"
        if ! gh label view "$name" --repo "$REPO" &>/dev/null 2>&1; then
            gh label create "$name" --color "$color" --description "$description" --repo "$REPO"
            echo "  Created label: $name"
        else
            echo "  Label exists: $name"
        fi
    }

    create_label_if_missing "forge-source-change"      "d93f0b" "PR modifies Retort source files"
    create_label_if_missing "needs-maintainer-review"   "e4e669" "Requires maintainer review before merge"
    create_label_if_missing "dependencies"              "0075ca" "Dependency updates"
    create_label_if_missing "breaking-change"           "b60205" "Contains breaking changes"
    create_label_if_missing "security"                  "d93f0b" "Security-related changes"
fi

echo ""

# =============================================================================
# Summary
# =============================================================================

echo "=== Setup Complete ==="
echo ""
echo "Configured:"
echo "  Branch protection ($BRANCH):"
echo "    - Required status checks (strict: true)"
echo "    - Required PR reviews: 1 approval(s), dismiss stale: true, CODEOWNERS: true"
echo "    - Last push approval: false"
echo "    - Conversation resolution: true"
echo "    - Linear history: true"
echo "    - Enforce admins: false"
echo "    - Force pushes: false | Deletions: false"

echo "  Repository settings:"
echo "    - Squash merge: true | Merge commits: false | Rebase: false"
echo "    - Delete branch on merge: true"
echo "    - Auto-merge: false"

echo "  Code scanning:"

echo "    - CodeQL: security=high_or_higher, alerts=errors"

echo "  Copilot code review:"
echo "    - Auto-request: enabled"
echo "    - Review new pushes: true"
echo "    - Review draft PRs: true"

echo ""
echo "Run 'gh api /repos/$REPO/branches/$BRANCH/protection' to verify."
