/**
 * Retort — .retortconfig Read/Write Utilities
 * Provides helpers for loading and persisting the project-level .retortconfig file.
 */
import { existsSync, readFileSync, writeFileSync } from 'fs';
import yaml from 'js-yaml';
import { resolve } from 'path';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const CONFIG_FILE_NAME = '.retortconfig';

const CONFIG_HEADER = [
  '# =============================================================================',
  '# .retortconfig — Project configuration for the Retort framework',
  '# Generated by `retort init` — edit as needed.',
  '# Null values (~) indicate explicitly disabled agents.',
  '# =============================================================================',
  '',
].join('\n');

// ---------------------------------------------------------------------------
// Serialization
// ---------------------------------------------------------------------------

/**
 * Serialize config object to YAML string with null rendered as ~ (tilde).
 */
function serializeConfig(config) {
  const raw = yaml.dump(config, {
    lineWidth: 120,
    noRefs: true,
    sortKeys: false,
    quotingType: '"',
    forceQuotes: false,
  });

  return raw
    .replace(/: null(\n|$)/g, ': ~$1')
    .replace(/^- null$/gm, '- ~');
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

/**
 * Read and parse the .retortconfig file from `projectRoot`.
 * Returns the parsed config object, or null if the file does not exist.
 *
 * @param {string} projectRoot - Absolute path to the project root
 * @returns {object|null}
 */
export function readRetortConfig(projectRoot) {
  const configPath = resolve(projectRoot, CONFIG_FILE_NAME);
  if (!existsSync(configPath)) return null;

  try {
    return yaml.load(readFileSync(configPath, 'utf-8')) ?? null;
  } catch {
    return null;
  }
}

/**
 * Serialize `config` and write it to `<projectRoot>/.retortconfig`.
 * Adds a comment header and renders null values as ~ (tilde).
 *
 * @param {string} projectRoot - Absolute path to the project root
 * @param {object} config - Config object to serialize
 */
export function writeRetortConfig(projectRoot, config) {
  const configPath = resolve(projectRoot, CONFIG_FILE_NAME);
  const content = CONFIG_HEADER + serializeConfig(config);
  writeFileSync(configPath, content, 'utf-8');
}
