# ---------------------------------------------------------------------------
# setup-branch-protection.ps1
# Configures GitHub branch protection rules, repository settings, code
# scanning rulesets, and Copilot review for the default branch.
# Generated by AgentKit Forge — run once after initial setup.
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth status)
#   - Admin access to the repository
#   - GitHub Advanced Security enabled (for code scanning rulesets)
#
# Usage:
#   .github/scripts/setup-branch-protection.ps1 [-Branch {{defaultBranch}}] [-DryRun]
# ---------------------------------------------------------------------------

param(
    [string]$Branch = "{{defaultBranch}}",
    [switch]$DryRun,
    [switch]$Help
)

$ErrorActionPreference = 'Stop'

if ($Help) {
    Write-Host "Usage: setup-branch-protection.ps1 [-Branch {{defaultBranch}}] [-DryRun]"
    Write-Host ""
    Write-Host "Configures GitHub branch protection for the specified branch."
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -Branch NAME   Branch to protect (default: {{defaultBranch}})"
    Write-Host "  -DryRun        Print the API payloads without applying"
    Write-Host "  -Help          Show this help"
    exit 0
}

# -- Verify prerequisites ---------------------------------------------------
if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Error "gh CLI is not installed. Install from https://cli.github.com/"
    exit 1
}

$authCheck = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "gh CLI is not authenticated. Run 'gh auth login' first."
    exit 1
}

# -- Detect repository -------------------------------------------------------
$Repo = gh repo view --json nameWithOwner -q '.nameWithOwner' 2>$null
if (-not $Repo) {
    Write-Error "Could not detect repository. Run this from within a git repo."
    exit 1
}

Write-Host "=== AgentKit Forge - Branch Protection Setup ==="
Write-Host ""
Write-Host "Repository: $Repo"
Write-Host "Branch:     $Branch"
Write-Host ""

# =============================================================================
# 1. Branch protection rules (legacy API)
# =============================================================================

$Payload = @{
    required_status_checks = @{
        strict   = ${{bpStrictStatusChecks}}
        contexts = @(
{{#each bpRequiredStatusChecks}}
            "{{.}}"
{{/each}}
        )
    }
    enforce_admins = ${{bpEnforceAdmins}}
    required_pull_request_reviews = @{
        required_approving_review_count = {{bpRequiredReviewCount}}
        dismiss_stale_reviews           = ${{bpDismissStaleReviews}}
        require_code_owner_reviews      = ${{bpRequireCodeOwnerReviews}}
        require_last_push_approval      = ${{bpRequireLastPushApproval}}
    }
    restrictions                    = $null
    required_linear_history         = ${{bpRequiredLinearHistory}}
    allow_force_pushes              = ${{bpAllowForcePushes}}
    allow_deletions                 = ${{bpAllowDeletions}}
    block_creations                 = ${{bpBlockCreations}}
    required_conversation_resolution = ${{bpRequiredConversationResolution}}
} | ConvertTo-Json -Depth 4

if ($DryRun) {
    Write-Host "[dry-run] Would apply the following branch protection to $Repo/$Branch:"
    Write-Host ""
    Write-Host $Payload
    Write-Host ""
} else {
    Write-Host "Applying branch protection rules..."
    $Payload | gh api --method PUT "/repos/$Repo/branches/$Branch/protection" --input -
    Write-Host "Branch protection applied."
}
Write-Host ""

# =============================================================================
# 2. Signed commits
# =============================================================================

{{#if bpRequireSignedCommits}}
if ($DryRun) {
    Write-Host "[dry-run] Would enable required signed commits on $Repo/$Branch"
} else {
    Write-Host "Enabling required signed commits..."
    try {
        gh api `
            --method POST `
            "/repos/$Repo/branches/$Branch/protection/required_signatures" `
            --header "Accept: application/vnd.github.zzzax-preview+json"
        Write-Host "Signed commits requirement applied."
    } catch {
        Write-Host "  Note: Signed commits require GitHub Pro/Team/Enterprise."
    }
}
Write-Host ""
{{/if}}

# =============================================================================
# 3. Repository settings (merge strategies, auto-delete, auto-merge)
# =============================================================================

$RepoSettings = @{
    allow_merge_commit     = ${{bpAllowMergeCommits}}
    allow_squash_merge     = ${{bpAllowSquashMerge}}
    allow_rebase_merge     = ${{bpAllowRebaseMerge}}
    delete_branch_on_merge = ${{bpDeleteBranchOnMerge}}
    allow_auto_merge       = ${{bpAllowAutoMerge}}
} | ConvertTo-Json -Depth 2

if ($DryRun) {
    Write-Host "[dry-run] Would apply the following repository settings to ${Repo}:"
    Write-Host ""
    Write-Host $RepoSettings
    Write-Host ""
} else {
    Write-Host "Applying repository merge settings..."
    $RepoSettings | gh api --method PATCH "/repos/$Repo" --input -
    Write-Host "Repository settings applied."
}
Write-Host ""

# =============================================================================
# 4. Code scanning ruleset (GitHub Rulesets API)
# =============================================================================

{{#if bpCodeScanningEnabled}}
$CodeScanningRuleset = @{
    name        = "code-scanning"
    target      = "branch"
    enforcement = "active"
    conditions  = @{
        ref_name = @{
            include = @("refs/heads/{{defaultBranch}}")
            exclude = @()
        }
    }
    rules = @(
        @{
            type       = "code_scanning"
            parameters = @{
                code_scanning_tools = @(
{{#each bpCodeScanningTools}}
                    @{
                        tool                     = "{{.name}}"
                        security_alerts_threshold = "{{.securityAlertThreshold}}"
                        alerts_threshold          = "{{.alertThreshold}}"
                    }
{{/each}}
                )
            }
        }
    )
} | ConvertTo-Json -Depth 6

if ($DryRun) {
    Write-Host "[dry-run] Would create/update code scanning ruleset on ${Repo}:"
    Write-Host ""
    Write-Host $CodeScanningRuleset
    Write-Host ""
} else {
    Write-Host "Configuring code scanning ruleset..."
    $existingId = gh api "/repos/$Repo/rulesets" --jq '.[] | select(.name == \"code-scanning\") | .id' 2>$null
    if ($existingId) {
        Write-Host "  Updating existing ruleset (ID: $existingId)..."
        $CodeScanningRuleset | gh api --method PUT "/repos/$Repo/rulesets/$existingId" --input -
    } else {
        Write-Host "  Creating new code scanning ruleset..."
        $CodeScanningRuleset | gh api --method POST "/repos/$Repo/rulesets" --input -
    }
    Write-Host "Code scanning ruleset applied."
}
Write-Host ""
{{/if}}

# =============================================================================
# 5. Copilot code review
# =============================================================================

{{#if bpCopilotReviewEnabled}}
$CopilotReview = @{
    enabled                    = $true
    review_new_pushes          = ${{bpCopilotReviewNewPushes}}
    review_draft_pull_requests = ${{bpCopilotReviewDraftPRs}}
} | ConvertTo-Json -Depth 2

if ($DryRun) {
    Write-Host "[dry-run] Would enable Copilot code review on ${Repo}:"
    Write-Host ""
    Write-Host $CopilotReview
    Write-Host ""
} else {
    Write-Host "Enabling Copilot code review..."
    # Note: Requires GitHub Copilot subscription with code review enabled for the organization.
    # Endpoint may return 404 if Copilot code review is not available for this repo.
    try {
        $CopilotReview | gh api --method PUT "/repos/$Repo/copilot/code_review" --input -
        Write-Host "Copilot code review configured."
    } catch {
        Write-Host "  Note: Copilot code review requires a Copilot-enabled organization."
    }
}
Write-Host ""
{{/if}}

# =============================================================================
# 6. Merge queue
# =============================================================================

{{#if bpMergeQueueEnabled}}
$MergeQueueRuleset = @{
    name        = "merge-queue"
    target      = "branch"
    enforcement = "active"
    conditions  = @{
        ref_name = @{
            include = @("refs/heads/{{defaultBranch}}")
            exclude = @()
        }
    }
    rules = @(
        @{
            type       = "merge_queue"
            parameters = @{
                merge_method                 = "{{bpMergeQueueMethod}}"
                min_entries_to_merge         = {{bpMergeQueueMinGroupSize}}
                max_entries_to_merge         = {{bpMergeQueueMaxGroupSize}}
                grouping_strategy            = "ALLGREEN"
                check_response_timeout_minutes = 60
            }
        }
    )
} | ConvertTo-Json -Depth 6

if ($DryRun) {
    Write-Host "[dry-run] Would create/update merge queue ruleset on ${Repo}:"
    Write-Host ""
    Write-Host $MergeQueueRuleset
    Write-Host ""
} else {
    Write-Host "Configuring merge queue..."
    $existingMqId = gh api "/repos/$Repo/rulesets" --jq '.[] | select(.name == \"merge-queue\") | .id' 2>$null
    if ($existingMqId) {
        Write-Host "  Updating existing merge queue ruleset (ID: $existingMqId)..."
        $MergeQueueRuleset | gh api --method PUT "/repos/$Repo/rulesets/$existingMqId" --input -
    } else {
        Write-Host "  Creating new merge queue ruleset..."
        $MergeQueueRuleset | gh api --method POST "/repos/$Repo/rulesets" --input -
    }
    Write-Host "Merge queue configured."
}
Write-Host ""
{{/if}}

# =============================================================================
# 7. Labels
# =============================================================================

Write-Host "Ensuring labels exist..."

function New-LabelIfMissing {
    param([string]$Name, [string]$Color, [string]$Description)

    $existing = gh label view $Name --repo $Repo 2>$null
    if ($LASTEXITCODE -ne 0) {
        gh label create $Name --color $Color --description $Description --repo $Repo
        Write-Host "  Created label: $Name"
    } else {
        Write-Host "  Label exists: $Name"
    }
}

New-LabelIfMissing "forge-source-change"    "d93f0b" "PR modifies AgentKit Forge source files"
New-LabelIfMissing "needs-maintainer-review" "e4e669" "Requires maintainer review before merge"
New-LabelIfMissing "dependencies"           "0075ca" "Dependency updates"
New-LabelIfMissing "breaking-change"        "b60205" "Contains breaking changes"
New-LabelIfMissing "security"               "d93f0b" "Security-related changes"

Write-Host ""

# =============================================================================
# Summary
# =============================================================================

Write-Host "=== Setup Complete ==="
Write-Host ""
Write-Host "Configured:"
Write-Host "  Branch protection ($Branch):"
Write-Host "    - Required status checks (strict: {{bpStrictStatusChecks}})"
Write-Host "    - Required PR reviews: {{bpRequiredReviewCount}} approval(s), dismiss stale: {{bpDismissStaleReviews}}, CODEOWNERS: {{bpRequireCodeOwnerReviews}}"
Write-Host "    - Last push approval: {{bpRequireLastPushApproval}}"
Write-Host "    - Conversation resolution: {{bpRequiredConversationResolution}}"
Write-Host "    - Linear history: {{bpRequiredLinearHistory}}"
Write-Host "    - Enforce admins: {{bpEnforceAdmins}}"
Write-Host "    - Force pushes: {{bpAllowForcePushes}} | Deletions: {{bpAllowDeletions}}"
{{#if bpRequireSignedCommits}}
Write-Host "    - Signed commits: required"
{{/if}}
Write-Host "  Repository settings:"
Write-Host "    - Squash merge: {{bpAllowSquashMerge}} | Merge commits: {{bpAllowMergeCommits}} | Rebase: {{bpAllowRebaseMerge}}"
Write-Host "    - Delete branch on merge: {{bpDeleteBranchOnMerge}}"
Write-Host "    - Auto-merge: {{bpAllowAutoMerge}}"
{{#if bpCodeScanningEnabled}}
Write-Host "  Code scanning:"
{{#each bpCodeScanningTools}}
Write-Host "    - {{.name}}: security={{.securityAlertThreshold}}, alerts={{.alertThreshold}}"
{{/each}}
{{/if}}
{{#if bpCopilotReviewEnabled}}
Write-Host "  Copilot code review:"
Write-Host "    - Auto-request: enabled"
Write-Host "    - Review new pushes: {{bpCopilotReviewNewPushes}}"
Write-Host "    - Review draft PRs: {{bpCopilotReviewDraftPRs}}"
{{/if}}
{{#if bpMergeQueueEnabled}}
Write-Host "  Merge queue:"
Write-Host "    - Method: {{bpMergeQueueMethod}}"
Write-Host "    - Group size: {{bpMergeQueueMinGroupSize}}-{{bpMergeQueueMaxGroupSize}}"
{{/if}}
Write-Host ""
Write-Host "Run 'gh api /repos/$Repo/branches/$Branch/protection' to verify."
