#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# setup-branch-protection.sh
# Configures GitHub branch protection rules, repository settings, code
# scanning rulesets, and Copilot review for the default branch.
# Generated by AgentKit Forge — run once after initial setup.
#
# Prerequisites:
#   - gh CLI installed and authenticated (gh auth status)
#   - Admin access to the repository
#   - GitHub Advanced Security enabled (for code scanning rulesets)
#
# Usage:
#   .github/scripts/setup-branch-protection.sh [--branch {{defaultBranch}}] [--dry-run]
# ---------------------------------------------------------------------------
set -euo pipefail

# -- Defaults ---------------------------------------------------------------
BRANCH="{{defaultBranch}}"
DRY_RUN=false

# -- Parse arguments --------------------------------------------------------
while [[ $# -gt 0 ]]; do
    case "$1" in
        --branch)  BRANCH="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        --help|-h)
            echo "Usage: $(basename "$0") [--branch {{defaultBranch}}] [--dry-run]"
            echo ""
            echo "Configures GitHub branch protection for the specified branch."
            echo ""
            echo "Options:"
            echo "  --branch NAME   Branch to protect (default: {{defaultBranch}})"
            echo "  --dry-run       Print the API payloads without applying"
            echo "  --help          Show this help"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# -- Verify prerequisites ---------------------------------------------------
if ! command -v gh &>/dev/null; then
    echo "Error: gh CLI is not installed. Install from https://cli.github.com/"
    exit 1
fi

if ! gh auth status &>/dev/null; then
    echo "Error: gh CLI is not authenticated. Run 'gh auth login' first."
    exit 1
fi

# -- Detect repository -------------------------------------------------------
REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null)
if [[ -z "$REPO" ]]; then
    echo "Error: Could not detect repository. Run this from within a git repo."
    exit 1
fi

echo "=== AgentKit Forge — Branch Protection Setup ==="
echo ""
echo "Repository: $REPO"
echo "Branch:     $BRANCH"
echo ""

# =============================================================================
# 1. Branch protection rules (legacy API)
# =============================================================================

PAYLOAD=$(cat <<'ENDJSON'
{
  "required_status_checks": {
    "strict": {{bpStrictStatusChecks}},
    "contexts": [
{{#each bpRequiredStatusChecks}}
      "{{.}}"{{/each}}
    ]
  },
  "enforce_admins": {{bpEnforceAdmins}},
  "required_pull_request_reviews": {
    "required_approving_review_count": {{bpRequiredReviewCount}},
    "dismiss_stale_reviews": {{bpDismissStaleReviews}},
    "require_code_owner_reviews": {{bpRequireCodeOwnerReviews}},
    "require_last_push_approval": {{bpRequireLastPushApproval}}
  },
  "restrictions": null,
  "required_linear_history": {{bpRequiredLinearHistory}},
  "allow_force_pushes": {{bpAllowForcePushes}},
  "allow_deletions": {{bpAllowDeletions}},
  "block_creations": {{bpBlockCreations}},
  "required_conversation_resolution": {{bpRequiredConversationResolution}}
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would apply the following branch protection to $REPO/$BRANCH:"
    echo ""
    echo "$PAYLOAD" | python3 -m json.tool 2>/dev/null || echo "$PAYLOAD"
    echo ""
else
    echo "Applying branch protection rules..."
    gh api \
        --method PUT \
        "/repos/$REPO/branches/$BRANCH/protection" \
        --input - <<< "$PAYLOAD"
    echo "Branch protection applied."
fi
echo ""

# =============================================================================
# 2. Signed commits
# =============================================================================

{{#if bpRequireSignedCommits}}
if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would enable required signed commits on $REPO/$BRANCH"
else
    echo "Enabling required signed commits..."
    gh api \
        --method POST \
        "/repos/$REPO/branches/$BRANCH/protection/required_signatures" \
        --header "Accept: application/vnd.github.zzzax-preview+json" \
        2>/dev/null || echo "  Note: Signed commits require GitHub Pro/Team/Enterprise."
    echo "Signed commits requirement applied."
fi
echo ""
{{/if}}

# =============================================================================
# 3. Repository settings (merge strategies, auto-delete, auto-merge)
# =============================================================================

REPO_SETTINGS=$(cat <<'ENDJSON'
{
  "allow_merge_commit": {{bpAllowMergeCommits}},
  "allow_squash_merge": {{bpAllowSquashMerge}},
  "allow_rebase_merge": {{bpAllowRebaseMerge}},
  "delete_branch_on_merge": {{bpDeleteBranchOnMerge}},
  "allow_auto_merge": {{bpAllowAutoMerge}}
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would apply the following repository settings to $REPO:"
    echo ""
    echo "$REPO_SETTINGS" | python3 -m json.tool 2>/dev/null || echo "$REPO_SETTINGS"
    echo ""
else
    echo "Applying repository merge settings..."
    gh api \
        --method PATCH \
        "/repos/$REPO" \
        --input - <<< "$REPO_SETTINGS"
    echo "Repository settings applied."
fi
echo ""

# =============================================================================
# 4. Code scanning ruleset (GitHub Rulesets API)
# =============================================================================

{{#if bpCodeScanningEnabled}}
CODE_SCANNING_RULESET=$(cat <<'ENDJSON'
{
  "name": "code-scanning",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/{{defaultBranch}}"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "code_scanning",
      "parameters": {
        "code_scanning_tools": [
{{#each bpCodeScanningTools}}
          {
            "tool": "{{.name}}",
            "security_alerts_threshold": "{{.securityAlertThreshold}}",
            "alerts_threshold": "{{.alertThreshold}}"
          }{{/each}}
        ]
      }
    }
  ]
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would create/update code scanning ruleset on $REPO:"
    echo ""
    echo "$CODE_SCANNING_RULESET" | python3 -m json.tool 2>/dev/null || echo "$CODE_SCANNING_RULESET"
    echo ""
else
    echo "Configuring code scanning ruleset..."
    # Check if a code-scanning ruleset already exists
    EXISTING_RULESET_ID=$(gh api "/repos/$REPO/rulesets" --jq '.[] | select(.name == "code-scanning") | .id' 2>/dev/null || true)
    if [[ -n "$EXISTING_RULESET_ID" ]]; then
        echo "  Updating existing ruleset (ID: $EXISTING_RULESET_ID)..."
        gh api \
            --method PUT \
            "/repos/$REPO/rulesets/$EXISTING_RULESET_ID" \
            --input - <<< "$CODE_SCANNING_RULESET"
    else
        echo "  Creating new code scanning ruleset..."
        gh api \
            --method POST \
            "/repos/$REPO/rulesets" \
            --input - <<< "$CODE_SCANNING_RULESET"
    fi
    echo "Code scanning ruleset applied."
fi
echo ""
{{/if}}

# =============================================================================
# 5. Copilot code review
# =============================================================================

{{#if bpCopilotReviewEnabled}}
COPILOT_REVIEW=$(cat <<'ENDJSON'
{
  "copilot_code_review": {
    "enabled": true
  }
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would enable Copilot code review on $REPO"
    echo "  Review new pushes: {{bpCopilotReviewNewPushes}}"
    echo "  Review draft PRs:  {{bpCopilotReviewDraftPRs}}"
else
    echo "Enabling Copilot code review..."
    # Copilot code review is configured via repository settings
    # Note: This requires Copilot Enterprise or a Copilot-enabled organization
    gh api \
        --method PATCH \
        "/repos/$REPO" \
        --input - <<< "$COPILOT_REVIEW" \
        2>/dev/null || echo "  Note: Copilot code review requires Copilot Enterprise."
    echo "Copilot code review configured."
fi
echo ""
{{/if}}

# =============================================================================
# 6. Merge queue
# =============================================================================

{{#if bpMergeQueueEnabled}}
MERGE_QUEUE_RULESET=$(cat <<'ENDJSON'
{
  "name": "merge-queue",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/{{defaultBranch}}"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "merge_queue",
      "parameters": {
        "merge_method": "{{bpMergeQueueMethod}}",
        "min_entries_to_merge": {{bpMergeQueueMinGroupSize}},
        "max_entries_to_merge": {{bpMergeQueueMaxGroupSize}},
        "grouping_strategy": "ALLGREEN",
        "check_response_timeout_minutes": 60
      }
    }
  ]
}
ENDJSON
)

if [[ "$DRY_RUN" == "true" ]]; then
    echo "[dry-run] Would create/update merge queue ruleset on $REPO:"
    echo ""
    echo "$MERGE_QUEUE_RULESET" | python3 -m json.tool 2>/dev/null || echo "$MERGE_QUEUE_RULESET"
    echo ""
else
    echo "Configuring merge queue..."
    EXISTING_MQ_ID=$(gh api "/repos/$REPO/rulesets" --jq '.[] | select(.name == "merge-queue") | .id' 2>/dev/null || true)
    if [[ -n "$EXISTING_MQ_ID" ]]; then
        echo "  Updating existing merge queue ruleset (ID: $EXISTING_MQ_ID)..."
        gh api \
            --method PUT \
            "/repos/$REPO/rulesets/$EXISTING_MQ_ID" \
            --input - <<< "$MERGE_QUEUE_RULESET"
    else
        echo "  Creating new merge queue ruleset..."
        gh api \
            --method POST \
            "/repos/$REPO/rulesets" \
            --input - <<< "$MERGE_QUEUE_RULESET"
    fi
    echo "Merge queue configured."
fi
echo ""
{{/if}}

# =============================================================================
# 7. Labels
# =============================================================================

echo "Ensuring labels exist..."

create_label_if_missing() {
    local name="$1" color="$2" description="$3"
    if ! gh label view "$name" --repo "$REPO" &>/dev/null 2>&1; then
        gh label create "$name" --color "$color" --description "$description" --repo "$REPO"
        echo "  Created label: $name"
    else
        echo "  Label exists: $name"
    fi
}

create_label_if_missing "forge-source-change"      "d93f0b" "PR modifies AgentKit Forge source files"
create_label_if_missing "needs-maintainer-review"   "e4e669" "Requires maintainer review before merge"
create_label_if_missing "dependencies"              "0075ca" "Dependency updates"
create_label_if_missing "breaking-change"           "b60205" "Contains breaking changes"
create_label_if_missing "security"                  "d93f0b" "Security-related changes"

echo ""

# =============================================================================
# Summary
# =============================================================================

echo "=== Setup Complete ==="
echo ""
echo "Configured:"
echo "  Branch protection ($BRANCH):"
echo "    - Required status checks (strict: {{bpStrictStatusChecks}})"
echo "    - Required PR reviews: {{bpRequiredReviewCount}} approval(s), dismiss stale: {{bpDismissStaleReviews}}, CODEOWNERS: {{bpRequireCodeOwnerReviews}}"
echo "    - Last push approval: {{bpRequireLastPushApproval}}"
echo "    - Conversation resolution: {{bpRequiredConversationResolution}}"
echo "    - Linear history: {{bpRequiredLinearHistory}}"
echo "    - Enforce admins: {{bpEnforceAdmins}}"
echo "    - Force pushes: {{bpAllowForcePushes}} | Deletions: {{bpAllowDeletions}}"
{{#if bpRequireSignedCommits}}
echo "    - Signed commits: required"
{{/if}}
echo "  Repository settings:"
echo "    - Squash merge: {{bpAllowSquashMerge}} | Merge commits: {{bpAllowMergeCommits}} | Rebase: {{bpAllowRebaseMerge}}"
echo "    - Delete branch on merge: {{bpDeleteBranchOnMerge}}"
echo "    - Auto-merge: {{bpAllowAutoMerge}}"
{{#if bpCodeScanningEnabled}}
echo "  Code scanning:"
{{#each bpCodeScanningTools}}
echo "    - {{.name}}: security={{.securityAlertThreshold}}, alerts={{.alertThreshold}}"
{{/each}}
{{/if}}
{{#if bpCopilotReviewEnabled}}
echo "  Copilot code review:"
echo "    - Auto-request: enabled"
echo "    - Review new pushes: {{bpCopilotReviewNewPushes}}"
echo "    - Review draft PRs: {{bpCopilotReviewDraftPRs}}"
{{/if}}
{{#if bpMergeQueueEnabled}}
echo "  Merge queue:"
echo "    - Method: {{bpMergeQueueMethod}}"
echo "    - Group size: {{bpMergeQueueMinGroupSize}}-{{bpMergeQueueMaxGroupSize}}"
{{/if}}
echo ""
echo "Run 'gh api /repos/$REPO/branches/$BRANCH/protection' to verify."
