#!/usr/bin/env bash
# GENERATED by Retort — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm --dir .agentkit retort:sync
# scripts/analyze-agents.sh
# Generates agent/team relationship matrices from spec files.
#
# Usage:
#   ./scripts/analyze-agents.sh [--output <path>] [--matrix <n>] [--format <fmt>]
#
# Options:
#   --output <path>   Output file (default: docs/agents/agent-team-matrix.md)
#   --matrix <n>      Specific matrix: 1-8, supplementary, all (default: all)
#   --format <fmt>    Output format: markdown, json (default: markdown)

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

node "$PROJECT_ROOT/.agentkit/engines/node/src/cli.mjs" analyze-agents "$@"
