# GENERATED by AgentKit Forge v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/agentkit-forge
# Regenerate: pnpm -C .agentkit agentkit:sync
<# agentkit: scaffold: managed #>
# scripts/analyze-agents.ps1
# Generates agent/team relationship matrices from spec files.
#
# Usage:
#   .\scripts\analyze-agents.ps1 [-Output <path>] [-Matrix <n>] [-Format <fmt>]

param(
    [string]$Output,
    [string]$Matrix,
    [string]$Format
)

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

$cliArgs = @('analyze-agents')
if ($Output) { $cliArgs += '--output', $Output }
if ($Matrix) { $cliArgs += '--matrix', $Matrix }
if ($Format) { $cliArgs += '--format', $Format }

node "$ProjectRoot/.agentkit/engines/node/src/cli.mjs" @cliArgs
