#!/usr/bin/env bash
# GENERATED by Retort — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm --dir .agentkit retort:sync
# scripts/check-documentation-requirement.sh
# Analyzes staged or changed files to determine whether PR documentation is required.
#
# ADVISORY ONLY — this script always exits 0. It reports the impact level of a
# change so an author can decide whether to write a history doc; it does not
# gate anything. Do not read its success as evidence that documentation exists.
#
# It previously honoured a STRICT env var (and its header advertised a --strict
# flag) that would exit 1 when documentation was required. No workflow ever set
# STRICT and no argv parsing for --strict was ever implemented, so both were
# dead: the step could not fail. They were removed rather than wired up so the
# script's behaviour matches its contract. Structural enforcement lives in
# validate-documentation.sh and validate-numbering.sh, which do exit non-zero.
#
# Usage (pre-commit hook):
#   ./scripts/check-documentation-requirement.sh
#
# Exit codes:
#   0 — always
#
# Environment variables:
#   GITHUB_BASE_REF  — set automatically in GitHub Actions PR workflows

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HISTORY_DIR="$REPO_ROOT/docs/history"

# ---------------------------------------------------------------------------
# Collect changed files
# ---------------------------------------------------------------------------

if [[ -n "${GITHUB_BASE_REF:-}" ]]; then
  # Running inside GitHub Actions pull_request event
  CHANGED_FILES=$(git diff --name-only "origin/${GITHUB_BASE_REF}" HEAD 2>/dev/null || git diff --name-only HEAD~1 HEAD)
else
  # Running locally — inspect staged files, fall back to last commit
  CHANGED_FILES=$(git diff --cached --name-only 2>/dev/null)
  if [[ -z "$CHANGED_FILES" ]]; then
    CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD 2>/dev/null || true)
  fi
fi

if [[ -z "$CHANGED_FILES" ]]; then
  echo "ℹ️  No changed files detected."
  exit 0
fi

# ---------------------------------------------------------------------------
# Impact assessment
# ---------------------------------------------------------------------------

IMPACT_HIGH=false
IMPACT_MEDIUM=false

while IFS= read -r file; do
  # High impact: project files, CI, security configs, infrastructure
  if [[ "$file" == *.csproj || "$file" == package.json || "$file" == Cargo.toml || \
        "$file" == go.mod || "$file" == pyproject.toml || "$file" == build.gradle || \
        "$file" == .github/workflows/*.yml || "$file" == .github/workflows/*.yaml || \
        "$file" == Dockerfile* || "$file" == docker-compose*.yml || \
        "$file" == **/terraform/**/*.tf || "$file" == **/infra/**/*.tf ]]; then
    IMPACT_HIGH=true
  # Medium impact: source code files
  elif [[ "$file" == src/**/*.cs || "$file" == src/**/*.ts || "$file" == src/**/*.tsx || \
          "$file" == src/**/*.py || "$file" == src/**/*.rs || "$file" == src/**/*.go || \
          "$file" == lib/**/*.* || "$file" == packages/**/*.* ]]; then
    IMPACT_MEDIUM=true
  fi
done <<< "$CHANGED_FILES"

# ---------------------------------------------------------------------------
# Count changed files
# ---------------------------------------------------------------------------

CHANGED_COUNT=$(echo "$CHANGED_FILES" | wc -l | tr -d ' ')

if [[ "$CHANGED_COUNT" -gt 50 ]]; then
  IMPACT_HIGH=true
fi

# ---------------------------------------------------------------------------
# Check if documentation already exists for this branch/PR
# ---------------------------------------------------------------------------

# Count history docs that have been staged or added in this branch
HISTORY_DOCS=0
if [[ -n "${GITHUB_BASE_REF:-}" ]]; then
  HISTORY_DOCS=$(git diff --name-only "origin/${GITHUB_BASE_REF}" HEAD -- 'docs/history/**/*.md' 2>/dev/null | grep -v 'README\.md\|TEMPLATE-' | wc -l | tr -d ' ' || echo 0)
else
  HISTORY_DOCS=$(git diff --cached --name-only -- 'docs/history/*.md' 'docs/history/**/*.md' 2>/dev/null | grep -v 'README\.md\|TEMPLATE-' | wc -l | tr -d ' ' || echo 0)
fi

# ---------------------------------------------------------------------------
# Output assessment
# ---------------------------------------------------------------------------

if [[ "$IMPACT_HIGH" == true ]]; then
  echo "⚠️  HIGH IMPACT change detected — documentation required"
  echo "   Changed files: $CHANGED_COUNT"
  if [[ "$HISTORY_DOCS" -gt 0 ]]; then
    echo "✅ Documentation found ($HISTORY_DOCS new doc(s) in docs/history/)"
    exit 0
  else
    echo "   Run: ./scripts/create-doc.sh <type> \"<title>\" <pr-number>"
    echo "   See: docs/engineering/06_pr_documentation.md"
  fi
elif [[ "$IMPACT_MEDIUM" == true ]]; then
  echo "ℹ️  MEDIUM IMPACT change detected — documentation recommended"
  echo "   Run: ./scripts/create-doc.sh <type> \"<title>\" <pr-number>"
else
  echo "✅ LOW IMPACT change — documentation optional"
fi

exit 0
