#!/usr/bin/env bash
# GENERATED by AgentKit Forge v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/agentkit-forge
# Regenerate: pnpm -C .agentkit agentkit:sync
# =============================================================================
# consolidate-branches.sh — Merge all unmerged feature branches into one
# =============================================================================
# Usage: scripts/consolidate-branches.sh [base-branch] [--dry-run] [--skip=branch1,branch2]
#
# Discovers all local and remote branches not yet merged into <base-branch>,
# filters out protected branches, and merges them one by one into the current
# branch. Uses resolve-merge.sh for auto-resolution of generated files.
#
# Arguments:
#   base-branch   Branch to check "merged" status against (default: main)
#   --dry-run     List branches that would be merged without doing anything
#   --skip=X,Y    Comma-separated list of branch names to skip
#
# Examples:
#   scripts/consolidate-branches.sh                    # merge all into current
#   scripts/consolidate-branches.sh dev --dry-run      # preview what would merge
#   scripts/consolidate-branches.sh main --skip=wip/experiment
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colours (disabled when piped)
if [ -t 1 ]; then
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  CYAN='\033[0;36m'
  BOLD='\033[1m'
  NC='\033[0m'
else
  GREEN='' YELLOW='' RED='' CYAN='' BOLD='' NC=''
fi

info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()   { echo -e "${RED}[error]${NC} $*"; }

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
BASE_BRANCH="main"
DRY_RUN=false
SKIP_BRANCHES=""

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
    --skip=*)  SKIP_BRANCHES="${arg#--skip=}" ;;
    -*)        err "Unknown flag: $arg"; exit 1 ;;
    *)         BASE_BRANCH="$arg" ;;
  esac
done

cd "$REPO_ROOT"

CURRENT_BRANCH="$(git branch --show-current)"
if [ -z "$CURRENT_BRANCH" ]; then
  err "Not on a branch (detached HEAD). Checkout a branch first."
  exit 1
fi

# ---------------------------------------------------------------------------
# Protected branches — never auto-merge these
# ---------------------------------------------------------------------------
PROTECTED_BRANCHES="main master develop release"

is_protected() {
  local branch="$1"
  for p in $PROTECTED_BRANCHES; do
    [ "$branch" = "$p" ] && return 0
  done
  return 1
}

is_skipped() {
  local branch="$1"
  if [ -n "$SKIP_BRANCHES" ]; then
    IFS=',' read -ra SKIPS <<< "$SKIP_BRANCHES"
    for s in "${SKIPS[@]}"; do
      [ "$branch" = "$s" ] && return 0
    done
  fi
  return 1
}

# ---------------------------------------------------------------------------
# 1. Fetch all remotes
# ---------------------------------------------------------------------------
info "Fetching all remotes..."
git fetch --all --prune 2>/dev/null || warn "Fetch failed — continuing with local state"

# ---------------------------------------------------------------------------
# 2. Discover unmerged branches
# ---------------------------------------------------------------------------
info "Finding branches not merged into ${BASE_BRANCH}..."

# Get all remote branches not merged into base
UNMERGED=()
while IFS= read -r ref; do
  [ -z "$ref" ] && continue
  # Strip 'origin/' prefix for display
  branch="${ref#origin/}"

  # Skip current branch, base branch, HEAD pointer
  [ "$branch" = "$CURRENT_BRANCH" ] && continue
  [ "$branch" = "$BASE_BRANCH" ] && continue
  [ "$branch" = "HEAD" ] && continue

  # Skip protected branches
  is_protected "$branch" && continue

  # Skip user-specified branches
  is_skipped "$branch" && continue

  UNMERGED+=("$branch")
done < <(git branch -r --no-merged "origin/${BASE_BRANCH}" 2>/dev/null | sed 's/^[* ]*//' | sort)

# Also check local-only branches (not on remote)
while IFS= read -r branch; do
  [ -z "$branch" ] && continue
  [ "$branch" = "$CURRENT_BRANCH" ] && continue
  [ "$branch" = "$BASE_BRANCH" ] && continue
  is_protected "$branch" && continue
  is_skipped "$branch" && continue

  # Check if already in UNMERGED list
  already=false
  for u in "${UNMERGED[@]+"${UNMERGED[@]}"}"; do
    [ "$u" = "$branch" ] && already=true && break
  done
  $already && continue

  UNMERGED+=("$branch")
done < <(git branch --no-merged "$BASE_BRANCH" 2>/dev/null | sed 's/^[* ]*//' | sort)

if [ ${#UNMERGED[@]} -eq 0 ]; then
  ok "No unmerged branches found. Everything is up to date with ${BASE_BRANCH}."
  exit 0
fi

# ---------------------------------------------------------------------------
# 3. Display plan
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}Branch Consolidation Plan${NC}"
echo -e "${BOLD}========================${NC}"
echo ""
echo -e "  Current branch:  ${GREEN}${CURRENT_BRANCH}${NC}"
echo -e "  Base branch:     ${CYAN}${BASE_BRANCH}${NC}"
echo -e "  Branches to merge: ${#UNMERGED[@]}"
echo ""

for i in "${!UNMERGED[@]}"; do
  branch="${UNMERGED[$i]}"
  # Get commit count ahead of base
  ahead=$(git rev-list --count "origin/${BASE_BRANCH}..origin/${branch}" 2>/dev/null || echo "?")
  echo -e "  $((i + 1)). ${YELLOW}${branch}${NC}  (${ahead} commits ahead)"
done

echo ""

if $DRY_RUN; then
  info "Dry run — no changes made."
  exit 0
fi

# ---------------------------------------------------------------------------
# 4. Merge each branch
# ---------------------------------------------------------------------------
MERGED=()
FAILED=()
SKIPPED_DIRTY=()

for branch in "${UNMERGED[@]}"; do
  echo ""
  echo -e "${BOLD}─────────────────────────────────────────${NC}"
  info "Merging ${branch} ($(( ${#MERGED[@]} + ${#FAILED[@]} + 1 ))/${#UNMERGED[@]})..."

  # Check for uncommitted changes before each merge
  local_stashed=false
  if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    warn "Uncommitted changes detected. Stashing before merge..."
    if git stash push -m "consolidate-branches: before merging ${branch}" 2>/dev/null; then
      local_stashed=true
    fi
  fi

  # Try merging from remote first, fall back to local
  merge_ref="origin/${branch}"
  if ! git rev-parse --verify "$merge_ref" &>/dev/null; then
    merge_ref="$branch"
  fi

  merge_output=$(git merge "$merge_ref" --no-edit 2>&1) && {
    ok "Merged ${branch} cleanly."
    MERGED+=("$branch")
    continue
  }

  # Check if it's a conflict or other error
  if echo "$merge_output" | grep -qF "CONFLICT"; then
    warn "Conflicts merging ${branch}. Attempting auto-resolution..."

    # Use resolve-merge logic inline (auto-resolve generated files)
    auto_resolved=0
    while IFS= read -r file; do
      [ -z "$file" ] && continue
      case "$file" in
        .claude/*|.cursor/*|.windsurf/*|.roo/*|.clinerules/*|.github/instructions/*|\
        .github/copilot-instructions.md|.github/PULL_REQUEST_TEMPLATE.md|\
        .github/agents/*|.github/chatmodes/*|.github/prompts/*|\
        .agents/*|.gemini/*|docs/*/README.md|\
        AGENTS.md|UNIFIED_AGENT_TEAMS.md|COMMAND_GUIDE.md|QUALITY_GATES.md|\
        RUNBOOK_AI.md|CONTRIBUTING.md)
          git checkout --theirs -- "$file" 2>/dev/null && git add "$file" 2>/dev/null
          ok "  Auto-resolved: $file"
          auto_resolved=$((auto_resolved + 1))
          ;;
        pnpm-lock.yaml|.agentkit/pnpm-lock.yaml|package-lock.json|yarn.lock|.agentkit/yarn.lock)
          git checkout --theirs -- "$file" 2>/dev/null && git add "$file" 2>/dev/null
          ok "  Auto-resolved (lockfile): $file"
          auto_resolved=$((auto_resolved + 1))
          ;;
      esac
    done < <(git diff --name-only --diff-filter=U 2>/dev/null)

    # Check if any conflicts remain
    remaining=$(git diff --name-only --diff-filter=U 2>/dev/null || true)
    if [ -z "$remaining" ]; then
      if git commit --no-edit 2>/dev/null; then
        ok "Merged ${branch} (${auto_resolved} auto-resolved)."
        MERGED+=("$branch")
      else
        err "Commit failed after auto-resolving ${branch} (exit code $?)."
        git merge --abort 2>/dev/null || true
        FAILED+=("$branch")
      fi
    else
      err "Unresolved conflicts merging ${branch}:"
      echo "$remaining" | while IFS= read -r f; do
        echo -e "  ${RED}✗${NC} $f"
      done
      warn "Aborting merge of ${branch}. Resolve manually or re-run with --skip=${branch}"
      git merge --abort 2>/dev/null || true
      FAILED+=("$branch")
    fi
  else
    err "Merge of ${branch} failed (not a conflict):"
    echo "  $merge_output"
    git merge --abort 2>/dev/null || true
    FAILED+=("$branch")
  fi

  # Restore stashed changes if we stashed before this merge
  if $local_stashed; then
    git stash pop 2>/dev/null || warn "Failed to restore stash for ${branch}"
  fi
done

# ---------------------------------------------------------------------------
# 5. Summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}═══════════════════════════════════════════${NC}"
echo -e "${BOLD}Consolidation Summary${NC}"
echo -e "${BOLD}═══════════════════════════════════════════${NC}"
echo ""
echo -e "  ${GREEN}Merged:${NC}  ${#MERGED[@]}/${#UNMERGED[@]}"

if [ ${#MERGED[@]} -gt 0 ]; then
  for b in "${MERGED[@]}"; do
    echo -e "    ${GREEN}✓${NC} $b"
  done
fi

if [ ${#FAILED[@]} -gt 0 ]; then
  echo ""
  echo -e "  ${RED}Failed:${NC}  ${#FAILED[@]}/${#UNMERGED[@]}"
  for b in "${FAILED[@]}"; do
    echo -e "    ${RED}✗${NC} $b"
  done
  echo ""
  warn "Re-run with: scripts/consolidate-branches.sh ${BASE_BRANCH} --skip=$(IFS=,; echo "${MERGED[*]:-}")"
fi

echo ""
if [ ${#MERGED[@]} -gt 0 ]; then
  info "Next steps:"
  echo "  1. Run: pnpm -C .agentkit agentkit:sync"
  echo "  2. Run: pnpm test"
  echo "  3. Review with: git log --oneline -20"
fi

exit ${#FAILED[@]}
