# GENERATED by Retort — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm --dir .agentkit retort:sync
<# agentkit: scaffold: managed #>
# scripts/create-doc.ps1
# Creates a new history document from the appropriate template.
#
# Usage:
#   ./scripts/create-doc.ps1 <type> "<title>" [pr-number]
#
# Arguments:
#   type        Document type: implementation | bugfix | feature | migration | issue | lesson
#   title       Human-readable title for the document
#   pr-number   Optional PR number to include in the document
#
# Examples:
#   ./scripts/create-doc.ps1 implementation "TreatWarningsAsErrors" 42
#   ./scripts/create-doc.ps1 bugfix "Null Reference in Auth" 43
#   ./scripts/create-doc.ps1 feature "User Authentication" 44
#   ./scripts/create-doc.ps1 migration "Upgrade to Node 22" 45

param(
  [Parameter(Mandatory = $true)]
  [ValidateSet('implementation', 'bugfix', 'feature', 'migration', 'issue', 'lesson')]
  [string]$Type,

  [Parameter(Mandatory = $true)]
  [string]$Title,

  [Parameter(Mandatory = $false)]
  [string]$PrNumber = ''
)

$ErrorActionPreference = 'Stop'

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot   = Split-Path -Parent $ScriptDir
$HistoryDir = Join-Path $RepoRoot 'docs' 'history'
$IndexFile  = Join-Path $HistoryDir '.index.json'

# ---------------------------------------------------------------------------
# Determine subdirectory from type
# ---------------------------------------------------------------------------

$SubdirMap = @{
  implementation = 'implementations'
  bugfix         = 'bug-fixes'
  feature        = 'features'
  migration      = 'migrations'
  issue          = 'issues'
  lesson         = 'lessons-learned'
}
$Subdir = $SubdirMap[$Type]

# ---------------------------------------------------------------------------
# Determine the next sequence number
#
# The .index.json counter alone is not trustworthy: documents created before
# the index existed were never registered, so the counter under-reports and
# hands out a number that is already taken on disk. Scan the destination
# directory for the highest existing NNNN- prefix and use whichever is larger.
# The index is still updated below so it remains a usable audit trail.
# ---------------------------------------------------------------------------

$DestDir = Join-Path $HistoryDir $Subdir
New-Item -ItemType Directory -Force -Path $DestDir | Out-Null

if (-not (Test-Path $IndexFile)) {
  $InitialIndex = @{
    nextNumber = 1
    sequences  = @{ implementation = 1; bugfix = 1; feature = 1; migration = 1; issue = 1; lesson = 1 }
    entries    = @()
  }
  $InitialIndex | ConvertTo-Json -Depth 5 | Set-Content -Encoding UTF8 $IndexFile
}

try {
  $Index = Get-Content $IndexFile -Raw | ConvertFrom-Json
} catch {
  # Corrupted index — rebuild it rather than aborting. The on-disk scan below
  # still yields a correct sequence number without it.
  Write-Warning "Could not parse $IndexFile — rebuilding it from scratch."
  $Index = [PSCustomObject]@{ sequences = [PSCustomObject]@{}; entries = @() }
}

if ($null -eq $Index.sequences) {
  $Index | Add-Member -NotePropertyName 'sequences' -NotePropertyValue ([PSCustomObject]@{}) -Force
}

$Counter = if ($Index.sequences.$Type) { [int]$Index.sequences.$Type } else { 1 }

$Highest = 0
Get-ChildItem -Path $DestDir -Filter '*.md' -File -ErrorAction SilentlyContinue | ForEach-Object {
  if ($_.Name -match '^(\d{4})-') {
    $Candidate = [int]$Matches[1]
    if ($Candidate -gt $Highest) { $Highest = $Candidate }
  }
}

$SeqNum  = [Math]::Max($Counter, $Highest + 1)
$Padded  = $SeqNum.ToString('0000')
$Date    = (Get-Date -Format 'yyyy-MM-dd')

# Sanitize title
$Slug = $Title.ToLower() -replace '[^a-z0-9]', '-' -replace '-+', '-' -replace '^-|-$', ''

$Filename = "${Padded}-${Date}-${Slug}-${Type}.md"
$DestFile = Join-Path $DestDir $Filename

# ---------------------------------------------------------------------------
# Copy template and substitute placeholders
# ---------------------------------------------------------------------------

$TemplateSrc = Join-Path $RepoRoot '.agentkit' 'templates' 'docs' 'history' $Subdir "TEMPLATE-${Type}.md"

if (-not (Test-Path $TemplateSrc)) {
  Write-Error "Template not found at $TemplateSrc"
  exit 1
}

# Render the PR reference as a clickable link when the GitHub slug is known,
# matching the "[#123](https://github.com/org/repo/pull/123)" convention used
# across existing history docs. Falls back to a bare "#123" otherwise.
$GithubSlug = "phoenixvc/retort"

$PrRef = if (-not $PrNumber) {
  '[#PR-Number]'
} elseif ($GithubSlug -and $GithubSlug -notmatch '\{\{') {
  "[#$PrNumber](https://github.com/$GithubSlug/pull/$PrNumber)"
} else {
  "#$PrNumber"
}

(Get-Content $TemplateSrc -Raw).
  Replace('[Feature/Change Name]', $Title).
  Replace('[Bug Description]',      $Title).
  Replace('[Feature Name]',         $Title).
  Replace('[Migration Name]',       $Title).
  Replace('[Issue Title]',          $Title).
  Replace('[Lesson Title]',         $Title).
  Replace('[YYYY-MM-DD]',           $Date).
  Replace('[#PR-Number]',           $PrRef) |
  Set-Content -Encoding UTF8 $DestFile

# ---------------------------------------------------------------------------
# Update index
# ---------------------------------------------------------------------------

if ($Index.sequences.$Type) {
  $Index.sequences.$Type = $SeqNum + 1
} else {
  $Index.sequences | Add-Member -NotePropertyName $Type -NotePropertyValue ($SeqNum + 1) -Force
}

$Entry = [PSCustomObject]@{
  number = $SeqNum
  type   = $Type
  title  = $Title
  date   = $Date
  pr     = $PrNumber
  file   = "$Subdir/$Filename"
}

if ($null -eq $Index.entries) {
  $Index | Add-Member -NotePropertyName 'entries' -NotePropertyValue @($Entry) -Force
} else {
  $Index.entries += $Entry
}

$Index | ConvertTo-Json -Depth 5 | Set-Content -Encoding UTF8 $IndexFile

Write-Host "Created: $DestFile"

# ---------------------------------------------------------------------------
# Update CHANGELOG.md
# ---------------------------------------------------------------------------

$ChangelogSectionMap = @{
  feature        = 'Added'
  implementation = 'Added'
  bugfix         = 'Fixed'
  migration      = 'Changed'
  issue          = ''
  lesson         = ''
}
$ChangelogSection = $ChangelogSectionMap[$Type]

# CHANGELOG.md lives at the repository root, so the link must be repo-relative
# ("docs/history/<subdir>/<file>") — not relative to docs/history/.
$ChangelogDocPath = "docs/history/$Subdir/$Filename"

$UpdateChangelogScript = Join-Path $ScriptDir 'update-changelog.ps1'
if (-not $ChangelogSection) {
  Write-Host "ℹ️  ${Type} records are not added to CHANGELOG.md — skipping changelog update."
} elseif (Test-Path $UpdateChangelogScript) {
  try {
    & $UpdateChangelogScript -Section $ChangelogSection -Description $Title `
      -PrNumber $PrNumber -HistoryDoc $ChangelogDocPath
  } catch {
    Write-Warning "Could not update CHANGELOG.md — please add the entry manually."
  }
} else {
  Write-Host "ℹ️  update-changelog.ps1 not found — skipping changelog update."
}
