#!/usr/bin/env bash
# GENERATED by Retort v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm -C .agentkit retort:sync
# =============================================================================
# resolve-merge.sh — Apply standard merge conflict resolutions
# =============================================================================
# Usage: scripts/resolve-merge.sh [target-branch]
#
# Merges origin/<target-branch> into the current branch and auto-resolves
# generated/framework-managed files per the Retort merge resolution matrix.
# Remaining conflicts (engine source, spec files) are listed for manual review.
# =============================================================================
set -euo pipefail

TARGET="${1:-main}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Colours (disabled when piped)
if [ -t 1 ]; then
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  RED='\033[0;31m'
  CYAN='\033[0;36m'
  NC='\033[0m'
else
  GREEN='' YELLOW='' RED='' CYAN='' NC=''
fi

info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()   { echo -e "${RED}[error]${NC} $*"; }

cd "$REPO_ROOT"

# ---------------------------------------------------------------------------
# 1. Fetch and attempt merge
# ---------------------------------------------------------------------------
info "Fetching origin/${TARGET}..."
git fetch origin "$TARGET" 2>/dev/null || {
  err "Failed to fetch origin/${TARGET}. Check your remote."
  exit 1
}

CURRENT_BRANCH="$(git branch --show-current)"
info "Merging origin/${TARGET} into ${CURRENT_BRANCH}..."

merge_output=$(git merge "origin/${TARGET}" --no-edit 2>&1) && {
  ok "Merge completed cleanly — no conflicts."
  exit 0
}

# Distinguish real merge conflicts from other failures
if ! echo "$merge_output" | grep -qF "CONFLICT"; then
  err "Merge failed for a reason other than conflicts:"
  echo "$merge_output"
  exit 1
fi

info "Merge conflicts detected. Applying resolution matrix..."

# ---------------------------------------------------------------------------
# 2. Auto-resolve generated files (KEEP_THEIRS — accept upstream)
# ---------------------------------------------------------------------------
GENERATED_PATTERNS=(
  '.agents/skills/*/SKILL.md'
  '.github/agents/*.agent.md'
  '.github/chatmodes/*.chatmode.md'
  '.github/prompts/*.prompt.md'
  'docs/*/README.md'
  '.github/copilot-instructions.md'
  '.github/PULL_REQUEST_TEMPLATE.md'
)

auto_resolved=0
for pattern in "${GENERATED_PATTERNS[@]}"; do
  # Find conflicted files matching this pattern
  while IFS= read -r file; do
    [ -z "$file" ] && continue
    if git checkout --theirs -- "$file" 2>/dev/null; then
      git add "$file" 2>/dev/null
      ok "Auto-resolved (accept upstream): $file"
      auto_resolved=$((auto_resolved + 1))
    fi
  done < <(git diff --name-only --diff-filter=U | grep -E "$pattern" 2>/dev/null || true)
done

# ---------------------------------------------------------------------------
# 3. Auto-resolve lockfiles (KEEP_THEIRS — accept upstream, regenerate later)
# ---------------------------------------------------------------------------
LOCKFILE_PATTERNS=(
  'pnpm-lock.yaml'
  '.agentkit/pnpm-lock.yaml'
  'package-lock.json'
  '.agentkit/package-lock.json'
)

for lockfile in "${LOCKFILE_PATTERNS[@]}"; do
  if git diff --name-only --diff-filter=U | grep -qx "$lockfile" 2>/dev/null; then
    if git checkout --theirs -- "$lockfile" 2>/dev/null; then
      git add "$lockfile" 2>/dev/null
      ok "Auto-resolved (accept upstream): $lockfile"
      auto_resolved=$((auto_resolved + 1))
    fi
  fi
done

# ---------------------------------------------------------------------------
# 4. Auto-resolve generated config (KEEP_THEIRS)
# ---------------------------------------------------------------------------
GENERATED_CONFIGS=(
  '.gemini/config.yaml'
)

for config in "${GENERATED_CONFIGS[@]}"; do
  if git diff --name-only --diff-filter=U | grep -qx "$config" 2>/dev/null; then
    if git checkout --theirs -- "$config" 2>/dev/null; then
      git add "$config" 2>/dev/null
      ok "Auto-resolved (accept upstream): $config"
      auto_resolved=$((auto_resolved + 1))
    fi
  fi
done

# ---------------------------------------------------------------------------
# 5. Report remaining conflicts
# ---------------------------------------------------------------------------
REMAINING="$(git diff --name-only --diff-filter=U 2>/dev/null || true)"

echo ""
info "Auto-resolved: ${auto_resolved} file(s)"

if [ -n "$REMAINING" ]; then
  echo ""
  warn "Manual merge required for the following file(s):"
  echo ""
  while IFS= read -r file; do
    [ -z "$file" ] && continue
    # Categorise for the developer
    case "$file" in
      .agentkit/engines/*) echo -e "  ${RED}[engine]${NC}  $file — semantic merge required (runtime logic)" ;;
      .agentkit/spec/*)    echo -e "  ${YELLOW}[spec]${NC}    $file — preserve both intents" ;;
      *)                   echo -e "  ${CYAN}[source]${NC}  $file" ;;
    esac
  done <<< "$REMAINING"
  echo ""
  info "Resolve the files above, then run: git add -A && git commit"
  exit 1
else
  ok "All conflicts resolved automatically."
  info "Committing merge..."
  git commit --no-edit
  ok "Merge committed successfully."

  # Suggest lockfile regeneration
  if git diff --name-only "HEAD~1..HEAD" | grep -q "lock\.\(yaml\|json\)$" 2>/dev/null; then
    echo ""
    warn "Lockfiles were updated. Consider running: pnpm install"
  fi
fi
