# GENERATED by AgentKit Forge v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/agentkit-forge
# Regenerate: pnpm -C .agentkit agentkit:sync
[CmdletBinding()]
param(
    [string]$Repo = '',
    [switch]$DryRun,
    [switch]$SkipDefaultBranch,
    [switch]$SkipProtection
)

$ErrorActionPreference = 'Stop'

if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Error "gh CLI is not installed. Install from https://cli.github.com/"
    exit 1
}

gh auth status 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Error "gh CLI is not authenticated. Run 'gh auth login' first."
    exit 1
}

if (-not $Repo) {
    $Repo = gh repo view --json nameWithOwner -q '.nameWithOwner' 2>$null
}

if (-not $Repo) {
    Write-Error "Could not determine repository. Pass -Repo <owner/name>."
    exit 1
}

Write-Host "=== AgentKit Branch Governance Setup ==="
Write-Host "Repository: $Repo"
Write-Host "DryRun:     $DryRun"
Write-Host ""

if (-not $SkipDefaultBranch) {
    if ($DryRun) {
        Write-Host "[dry-run] Would set default branch to 'main' for $Repo"
    } else {
        gh api --method PATCH "/repos/$Repo" -f default_branch='main' | Out-Null
        Write-Host "Default branch set to 'main'."
    }
}

$payload = @"
{
  "required_status_checks": {
    "strict": true,
    "contexts": [
      "Test",
      "Validate",
      "Branch Protection / branch-rules"
    ]
  },
  "enforce_admins": false,
  "required_pull_request_reviews": {
    "required_approving_review_count": 1,
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": true,
    "require_last_push_approval": false
  },
  "restrictions": null,
  "required_linear_history": true,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "block_creations": false,
  "required_conversation_resolution": true
}
"@

if (-not $SkipProtection) {
    foreach ($branch in @('main', 'main')) {
        if ($DryRun) {
            Write-Host "[dry-run] Would apply branch protection to $Repo/$branch"
            continue
        }
        $payload | gh api --method PUT "/repos/$Repo/branches/$branch/protection" --input - | Out-Null
        Write-Host "Branch protection applied to $branch."
    }
}

Write-Host ""
Write-Host "Done."
Write-Host "Verify with: gh api /repos/$Repo/branches/main/protection"
Write-Host "             gh api /repos/$Repo/branches/main/protection"
