# GENERATED by Retort — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm --dir .agentkit retort:sync
<# agentkit: scaffold: managed #>
# scripts/update-changelog.ps1
# Inserts an entry into the [Unreleased] section of CHANGELOG.md.
#
# Usage:
#   ./scripts/update-changelog.ps1 <section> "<description>" [pr-number] [history-doc-path]
#
# Arguments:
#   section          Changelog section: Added | Fixed | Changed | Removed | Security | Deprecated
#   description      Human-readable description of the change
#   PrNumber         Optional PR number (e.g. 42)
#   HistoryDoc       Optional relative path to the history document
#
# Examples:
#   ./scripts/update-changelog.ps1 Added "New user auth feature" 44
#   ./scripts/update-changelog.ps1 Fixed "Null reference in login" 43 `
#     "docs/history/bug-fixes/0001-2026-03-01-null-reference-bugfix.md"

param(
  [Parameter(Mandatory = $true)]
  [ValidateSet('Added', 'Fixed', 'Changed', 'Removed', 'Security', 'Deprecated')]
  [string]$Section,

  [Parameter(Mandatory = $true)]
  [string]$Description,

  [Parameter(Mandatory = $false)]
  [string]$PrNumber = '',

  [Parameter(Mandatory = $false)]
  [string]$HistoryDoc = ''
)

$ErrorActionPreference = 'Stop'

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot   = Split-Path -Parent $ScriptDir
$Changelog  = Join-Path $RepoRoot 'CHANGELOG.md'

if (-not (Test-Path $Changelog)) {
  Write-Error "CHANGELOG.md not found at $Changelog"
  exit 1
}

# ---------------------------------------------------------------------------
# Build the entry line
# ---------------------------------------------------------------------------

$Entry = "- $Description"

if ($PrNumber -and $HistoryDoc) {
  $Entry += " ([#${PrNumber}](../../pull/${PrNumber}), [history]($HistoryDoc))"
} elseif ($PrNumber) {
  $Entry += " ([#${PrNumber}](../../pull/${PrNumber}))"
} elseif ($HistoryDoc) {
  $Entry += " ([history]($HistoryDoc))"
}

# ---------------------------------------------------------------------------
# Insert entry via Node.js for reliable multiline editing
# ---------------------------------------------------------------------------

$NodeScript = @'
const [,, changelogPath, section, entry] = process.argv;
const fs = require('fs');
const content = fs.readFileSync(changelogPath, 'utf8');
const lines = content.split('\n');

const unreleasedIdx = lines.findIndex(l => /^## \[Unreleased\]/i.test(l));
if (unreleasedIdx === -1) {
  console.error('Error: could not find ## [Unreleased] section in CHANGELOG.md');
  process.exit(1);
}

// ...ending at the next ## heading or the --- footer, whichever comes first.
// Without the --- bound an insert can land inside the footer, or past the end
// of the file entirely when no released version follows.
let blockEnd = lines.findIndex(
  (l, i) => i > unreleasedIdx && (/^## /.test(l) || l.trim() === '---')
);
if (blockEnd === -1) blockEnd = lines.length;

const sectionHeader = `### ${section}`;
let sectionIdx = lines.findIndex((l, i) => i > unreleasedIdx && i < blockEnd && l.trim() === sectionHeader);

if (sectionIdx === -1) {
  // Section doesn't exist — append it at the end of the [Unreleased] block,
  // backing over any trailing blank lines so exactly one blank ends up either
  // side of the new heading and its entry
  let insertAt = blockEnd;
  while (insertAt > unreleasedIdx + 1 && lines[insertAt - 1].trim() === '') insertAt--;
  lines.splice(insertAt, 0, '', sectionHeader, '', entry);
} else {
  // Step over the header and the blank line beneath it, then past any existing
  // entries, so the entry joins the end of one contiguous list. Splicing
  // directly after the header would leave the heading with no blank line under
  // it and split the list in two — markdownlint MD022 and MD032.
  let insertAt = sectionIdx + 1;
  while (insertAt < blockEnd && lines[insertAt].trim() === '') insertAt++;
  while (
    insertAt < blockEnd &&
    lines[insertAt].trim() !== '' &&
    !lines[insertAt].startsWith('#') &&
    lines[insertAt].trim() !== '---'
  ) {
    insertAt++;
  }
  // An empty section leaves insertAt on the next heading (the blank-line scan
  // above stepped over the only blank), so a bare splice would butt the entry
  // straight against that heading and trip MD022/MD032 — the very rules this
  // branch exists to satisfy. Re-add the separating blank in that case.
  const atBoundary =
    insertAt >= blockEnd ||
    lines[insertAt].startsWith('#') ||
    lines[insertAt].trim() === '---';
  lines.splice(insertAt, 0, ...(atBoundary ? [entry, ''] : [entry]));
}

fs.writeFileSync(changelogPath, lines.join('\n'), 'utf8');
console.log(`Updated CHANGELOG.md — ${section}: ${entry}`);
'@

$TmpScript = [System.IO.Path]::GetTempFileName() + '.cjs'
Set-Content -Path $TmpScript -Value $NodeScript -Encoding UTF8
try {
  node $TmpScript $Changelog $Section $Entry
} finally {
  Remove-Item -Force $TmpScript -ErrorAction SilentlyContinue
}
