#!/usr/bin/env bash
# GENERATED by Retort v3.1.0 — DO NOT EDIT
# Source: .agentkit/spec + .agentkit/overlays/retort
# Regenerate: pnpm -C .agentkit retort:sync
# scripts/validate-numbering.sh
# Validates the sequential numbering of history documents against .index.json.
#
# Usage:
#   ./scripts/validate-numbering.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HISTORY_DIR="$REPO_ROOT/docs/history"
INDEX_FILE="$HISTORY_DIR/.index.json"

ERRORS=0

if [[ ! -f "$INDEX_FILE" ]]; then
  echo "ℹ️  No .index.json found at $INDEX_FILE — skipping numbering validation."
  exit 0
fi

# Check for duplicate sequence numbers per type
for subdir in implementations bug-fixes features migrations; do
  case "$subdir" in
    implementations) TYPE="implementation" ;;
    bug-fixes)       TYPE="bugfix" ;;
    features)        TYPE="feature" ;;
    migrations)      TYPE="migration" ;;
  esac

  DIR="$HISTORY_DIR/$subdir"
  if [[ ! -d "$DIR" ]]; then
    continue
  fi

  declare -A seen_numbers=()

  while IFS= read -r -d '' file; do
    base="$(basename "$file")"
    # Skip templates and READMEs
    if [[ "$base" == TEMPLATE-* || "$base" == README.md ]]; then
      continue
    fi
    # Extract leading 4-digit number
    if [[ "$base" =~ ^([0-9]{4})- ]]; then
      num="${BASH_REMATCH[1]}"
      if [[ -n "${seen_numbers[$num]+x}" ]]; then
        echo "❌ Duplicate number $num in $subdir/:"
        echo "   ${seen_numbers[$num]}"
        echo "   $base"
        ERRORS=$((ERRORS + 1))
      else
        seen_numbers[$num]="$base"
      fi
    fi
  done < <(find "$DIR" -maxdepth 1 -name "*.md" -print0 2>/dev/null || true)

  unset seen_numbers
done

if [[ "$ERRORS" -gt 0 ]]; then
  echo ""
  echo "Found $ERRORS numbering error(s)."
  exit 1
else
  echo "✅ Sequential numbering is valid."
fi
